# Generated by Django 6.0.6 on 2026-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_temporary_password_set_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtokenblacklist',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
