# Generated by Django 4.2.7 on 2026-04-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planning_governance_and_ai'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='planningaigovernancelog',
            new_name='planning_pl_organiz_a1197e_idx',
            old_name='planning_pl_organiz_95d70d_idx',
        ),
        migrations.RenameIndex(
            model_name='planningaigovernancelog',
            new_name='planning_pl_human_d_d20c9b_idx',
            old_name='planning_pl_human_d_5ca6c2_idx',
        ),
        migrations.RenameIndex(
            model_name='planningapprovalrecord',
            new_name='planning_pl_organiz_3584fe_idx',
            old_name='planning_pl_organiz_a4bbdd_idx',
        ),
        migrations.RenameIndex(
            model_name='planningapprovalrecord',
            new_name='planning_pl_referen_01d853_idx',
            old_name='planning_pl_referen_24cb51_idx',
        ),
        migrations.RenameIndex(
            model_name='planningversionrecord',
            new_name='planning_pl_organiz_49f381_idx',
            old_name='planning_pl_organiz_4d7304_idx',
        ),
        migrations.RenameIndex(
            model_name='planningversionrecord',
            new_name='planning_pl_entity__c648fb_idx',
            old_name='planning_pl_entity__26470f_idx',
        ),
    ]
