# Generated by Django 4.2.7 on 2026-03-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(default='Nueva conversación', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=20)),
                ('current_route', models.CharField(blank=True, max_length=255)),
                ('current_module', models.CharField(blank=True, max_length=80)),
                ('current_submodule', models.CharField(blank=True, max_length=120)),
                ('last_standard_focus', models.CharField(blank=True, max_length=80)),
                ('last_clause_focus', models.CharField(blank=True, max_length=40)),
                ('context_summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(unique=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('normative_policy', models.TextField(blank=True)),
                ('response_policy', models.TextField(blank=True)),
                ('citation_policy', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_prompt_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_prompt_configs',
            },
        ),
        migrations.CreateModel(
            name='AssistantOrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(unique=True)),
                ('primary_standards', models.JSONField(blank=True, default=list)),
                ('secondary_standards', models.JSONField(blank=True, default=list)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('risk_tolerance', models.CharField(blank=True, max_length=50)),
                ('organization_summary', models.TextField(blank=True)),
                ('preferred_response_style', models.CharField(default='pragmatic', max_length=50)),
                ('forbidden_topics', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assistant_org_profiles',
                'indexes': [models.Index(fields=['organization_id', 'updated_at'], name='assistant_o_organiz_9d30e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('role', models.CharField(choices=[('system', 'Sistema'), ('user', 'Usuario'), ('assistant', 'Asistente'), ('tool', 'Herramienta')], max_length=20)),
                ('content', models.TextField()),
                ('content_type', models.CharField(default='text', max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('token_usage_prompt', models.IntegerField(blank=True, null=True)),
                ('token_usage_completion', models.IntegerField(blank=True, null=True)),
                ('token_usage_total', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integration.assistantconversation')),
            ],
            options={
                'db_table': 'assistant_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('memory_type', models.CharField(choices=[('decision', 'Decision'), ('fact', 'Fact'), ('risk', 'Risk'), ('evidence', 'Evidence'), ('policy', 'Policy'), ('summary', 'Summary')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('module', models.CharField(blank=True, max_length=60)),
                ('standard_code', models.CharField(blank=True, max_length=40)),
                ('clause_reference', models.CharField(blank=True, max_length=40)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assistant_memory_items',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization_id', 'memory_type'], name='assistant_m_organiz_776209_idx'), models.Index(fields=['organization_id', 'module'], name='assistant_m_organiz_eda50f_idx'), models.Index(fields=['organization_id', 'standard_code'], name='assistant_m_organiz_a88473_idx'), models.Index(fields=['organization_id', 'is_active'], name='assistant_m_organiz_b34f7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('rating', models.SmallIntegerField()),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='integration.assistantconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='integration.assistantmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='integration.assistantconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['organization_id', 'conversation'], name='assistant_m_organiz_a9d660_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['organization_id', 'created_at'], name='assistant_m_organiz_08edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantfeedback',
            index=models.Index(fields=['organization_id', 'rating'], name='assistant_f_organiz_39aa81_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantfeedback',
            index=models.Index(fields=['organization_id', 'created_at'], name='assistant_f_organiz_bd6a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['organization_id', 'status'], name='assistant_c_organiz_6f500b_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['organization_id', 'updated_at'], name='assistant_c_organiz_87cf76_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['organization_id', 'user'], name='assistant_c_organiz_58cc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['organization_id', 'event_type'], name='assistant_a_organiz_723141_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['organization_id', 'created_at'], name='assistant_a_organiz_e5291d_idx'),
        ),
    ]
