# Generated by Django 4.2.7 on 2026-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('document_id', models.CharField(db_index=True, max_length=120)),
                ('chunk_index', models.PositiveSmallIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('source_type', models.CharField(choices=[('document', 'Documento'), ('policy', 'Política'), ('procedure', 'Procedimiento'), ('record', 'Registro'), ('manual', 'Manual'), ('regulation', 'Normativa externa'), ('memory_item', 'Elemento de memoria')], default='document', max_length=40)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, max_length=60)),
                ('standard_code', models.CharField(blank=True, max_length=40)),
                ('clause_reference', models.CharField(blank=True, max_length=40)),
                ('vector_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assistant_document_chunks',
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['organization_id', 'document_id'], name='assistant_d_organiz_2a51eb_idx'), models.Index(fields=['organization_id', 'module'], name='assistant_d_organiz_7ce3a9_idx'), models.Index(fields=['organization_id', 'standard_code'], name='assistant_d_organiz_c30429_idx'), models.Index(fields=['organization_id', 'is_active'], name='assistant_d_organiz_c1cb5f_idx')],
                'unique_together': {('organization_id', 'document_id', 'chunk_index', 'version')},
            },
        ),
    ]
