"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde backend/.env si existe
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


ENVIRONMENT = os.getenv('DJANGO_ENV', os.getenv('ENVIRONMENT', 'development')).strip().lower()
IS_PRODUCTION = ENVIRONMENT in ('production', 'prod')
IS_DEVELOPMENT = ENVIRONMENT in ('development', 'dev', 'local')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'change-this-dev-secret-key-before-deploy')
SMART3AI_SSO_JWT_SECRET = os.getenv('SMART3AI_SSO_JWT_SECRET', SECRET_KEY)
SMART3AI_SSO_ISSUER = os.getenv('SMART3AI_SSO_ISSUER', 'https://sso.smart3ai.local')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=False)

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,192.168.100.100,isosmart.local'
)

# Keep local reverse-proxy host aliases accepted even if .env ALLOWED_HOSTS is stale.
if not IS_PRODUCTION:
    for required_host in (
        'isosmart.smart3ai.local',
        'smart3ai.local',
    ):
        if required_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(required_host)

if IS_PRODUCTION:
    if SECRET_KEY in ('', 'change-this-dev-secret-key-before-deploy'):
        raise RuntimeError('SECRET_KEY must be set to a secure value in production')
    if DEBUG:
        raise RuntimeError('DEBUG must be disabled in production')
    if not ALLOWED_HOSTS:
        raise RuntimeError('ALLOWED_HOSTS must be configured in production')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'django_filters',
    'corsheaders',
    'authentication',
    'leadership',
    # Local apps
    'core',
    'ai_modules.common',
    'ai_modules.sca.apps.ScaConfig',      # Módulo SCA
    'ai_modules.sie.apps.SieConfig',      # Módulo SIE
    'ai_modules.asb.apps.AsbConfig',      # Módulo ASB
    'ai_modules.spm',                     # Módulo SPM 
    'integration',
    'resources',
    'planning',
    'operations',
    'performance',
    'improvement',
]

# Configuración de integración
ADMIN_APPS_INTEGRATION = {
    'BASE_URL': os.getenv('ADMIN_APPS_BASE_URL', 'http://127.0.0.1:8000/api/integration'),
    # Keep env override as primary source; fallback keeps local/dev auth integration functional.
    'API_KEY': os.getenv('ADMIN_APPS_API_KEY', 'isosmart-integration-key-2025'),
    'TIMEOUT': int(os.getenv('ADMIN_APPS_TIMEOUT', '10')),
    'CACHE_TTL': int(os.getenv('ADMIN_APPS_CACHE_TTL', '300')),
    'SYNC_USERS': _env_bool('ADMIN_APPS_SYNC_USERS', default=True),
}

# Patrones de URL por módulo
MODULE_URL_PATTERNS = {
    'SCA': [r'^/api/sca/'],
    'SIE': [r'^/api/sie/', r'^/api/stakeholders/'],
    'ASB': [r'^/api/scope/'],
    'SPM': [r'^/api/processes/'],
    'DOC': [r'^/api/documents/'],
    'RISK': [r'^/api/risks/'],
    'OBJ': [r'^/api/objectives/'],
    'LEAD': [r'^/api/leadership/'],
}

# Comercializacion de estandares ISO:
# - Fase inicial: solo ISO9001_2015
# - Para habilitar nuevas normas por organizacion, usar COMMERCIAL_ENABLED_STANDARDS_BY_ORG
COMMERCIAL_ENABLED_STANDARDS = ['ISO9001_2015']
COMMERCIAL_ENABLED_STANDARDS_BY_ORG = {
    # Ejemplo futuro:
    # 3: ['ISO9001_2015', 'ISO27001_2022'],
}

# Politica comercial de organizacion duena (Smart3AI)
OWNER_ORGANIZATION_ONLY_ACCESS = _env_bool('OWNER_ORGANIZATION_ONLY_ACCESS', default=True)
OWNER_ORGANIZATION_SLUG = os.getenv('OWNER_ORGANIZATION_SLUG', 'smart3ai')
OWNER_ORGANIZATION_NAME = os.getenv('OWNER_ORGANIZATION_NAME', 'Smart3AI')
OWNER_ORGANIZATION_EXTERNAL_ID = os.getenv('OWNER_ORGANIZATION_EXTERNAL_ID', '').strip()
OWNER_ORGANIZATION_BILLING_EXEMPT = _env_bool('OWNER_ORGANIZATION_BILLING_EXEMPT', default=True)
ALLOW_LOCAL_AUTH_BYPASS_FOR_TESTS = (
    IS_DEVELOPMENT
    and _env_bool('ALLOW_LOCAL_AUTH_BYPASS_FOR_TESTS', default=False)
)
LOCAL_AUTH_BYPASS_HOSTS = set(_env_list(
    'LOCAL_AUTH_BYPASS_HOSTS',
    default='127.0.0.1,localhost,testserver,isosmart.local,isosmart.smart3ai.local'
))

# Configuración de REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'integration.sso_auth.Smart3AISSOAuthentication',  # Centralized SSO JWT
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT authentication
        'rest_framework.authentication.SessionAuthentication',  # Session authentication para desarrollo
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON_RATE', '60/minute'),
        'user': os.getenv('THROTTLE_USER_RATE', '300/minute'),
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'backend.middleware.RequestIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'backend.middleware.CsrfExemptAPIMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.OrganizationMiddleware',
    'integration.middleware.ModuleAccessMiddleware',
    'integration.middleware.AdminAppsSyncMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'isosmart_main'),
        'USER': os.getenv('DB_USER', 'isosmart'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    },
    # Bases adicionales para IA y auditoría
    'ai_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('AI_DB_NAME', 'isosmart_ai'),
        'USER': os.getenv('AI_DB_USER', os.getenv('DB_USER', 'isosmart')),
        'PASSWORD': os.getenv('AI_DB_PASSWORD', os.getenv('DB_PASSWORD', '')),
        'HOST': os.getenv('AI_DB_HOST', os.getenv('DB_HOST', '127.0.0.1')),
        'PORT': os.getenv('AI_DB_PORT', os.getenv('DB_PORT', '5432')),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    },
    'audit_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('AUDIT_DB_NAME', 'isosmart_audit'),
        'USER': os.getenv('AUDIT_DB_USER', os.getenv('DB_USER', 'isosmart')),
        'PASSWORD': os.getenv('AUDIT_DB_PASSWORD', os.getenv('DB_PASSWORD', '')),
        'HOST': os.getenv('AUDIT_DB_HOST', os.getenv('DB_HOST', '127.0.0.1')),
        'PORT': os.getenv('AUDIT_DB_PORT', os.getenv('DB_PORT', '5432')),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
}

#Configurar modelo de usuario
AUTH_USER_MODEL = 'authentication.User'

#Configurar backends de autenticación
AUTHENTICATION_BACKENDS = [
    'integration.backends.AdminAppsAuthBackend',  # AdminApps integration auth
    'authentication.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

#Configurar JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SMART3AI_SSO_JWT_SECRET,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Configuración de asistente IA (streaming endpoint)
AI_ASSISTANT_API_URL = os.getenv('AI_ASSISTANT_API_URL', 'https://api.openai.com/v1/chat/completions')
AI_ASSISTANT_API_KEY = os.getenv('AI_ASSISTANT_API_KEY', '')
AI_ASSISTANT_MODEL = os.getenv('AI_ASSISTANT_MODEL', 'gpt-4o-mini')
AI_ASSISTANT_SUPPORTED_STANDARDS = os.getenv(
    'AI_ASSISTANT_SUPPORTED_STANDARDS',
    'ISO 9001, ISO 14001, ISO 45001, ISO 27001, ISO 42001'
)
AI_ASSISTANT_SYSTEM_PROMPT = os.getenv(
    'AI_ASSISTANT_SYSTEM_PROMPT',
    (
        'Eres el asistente virtual de ISO Smart. Responde en español de forma breve, precisa y accionable. '
        'Tu foco principal es orientar sobre sistemas de gestion, clausulas, evidencias, registros, riesgos, '
        'auditorias, no conformidades, acciones correctivas e implementacion por etapas. '
        'Normas prioritarias soportadas: {standards}. '
        'Si la consulta menciona una norma, responde alineado a esa norma. Si no la menciona, prioriza ISO 9001 '
        'como base y aclara cuando una recomendacion depende de la norma aplicable. '
        'No inventes requisitos normativos. Si falta contexto, indicalo y pide la informacion minima necesaria. '
        'Siempre sugiere el siguiente paso practico dentro del modulo actual cuando aplique.'
    ).format(standards=os.getenv(
        'AI_ASSISTANT_SUPPORTED_STANDARDS',
        'ISO 9001, ISO 14001, ISO 45001, ISO 27001, ISO 42001'
    ))
)

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@isosmart.local')
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:5173')
PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = int(os.getenv('PASSWORD_RESET_TOKEN_EXPIRY_MINUTES', '30'))
PASSWORD_RESET_WINDOW_MINUTES = int(os.getenv('PASSWORD_RESET_WINDOW_MINUTES', '60'))
PASSWORD_RESET_MAX_REQUESTS_PER_HOUR = int(os.getenv('PASSWORD_RESET_MAX_REQUESTS_PER_HOUR', '5'))
PASSWORD_HISTORY_COUNT = int(os.getenv('PASSWORD_HISTORY_COUNT', '5'))
TEMP_PASSWORD_MAX_AGE_DAYS = int(os.getenv('TEMP_PASSWORD_MAX_AGE_DAYS', '7'))
TEMP_PASSWORD_WARNING_DAYS = int(os.getenv('TEMP_PASSWORD_WARNING_DAYS', '2'))

# Login brute-force / account-lockout policy
LOGIN_MAX_ATTEMPTS = int(os.getenv('LOGIN_MAX_ATTEMPTS', '5'))
LOGIN_LOCKOUT_MINUTES = int(os.getenv('LOGIN_LOCKOUT_MINUTES', '15'))

# Security headers (enforced by Django SecurityMiddleware)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=IS_PRODUCTION)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000' if IS_PRODUCTION else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=IS_PRODUCTION)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', default=False)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)

# Configuración de Celery
CELERY_BROKER_URL = 'redis://localhost:6379/1'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Costa_Rica'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'America/Costa_Rica'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales de estáticos
STATICFILES_DIRS = []

# Finder de archivos estáticos
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de logs
LOG_DIR = Path(os.getenv('ISOSMART_LOG_DIR', BASE_DIR / 'logs' / 'ai'))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'backend.request_context.RequestIDLogFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} request_id={request_id} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = _env_list(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3001,http://127.0.0.1:3001,http://isosmart.local'
)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-request-id',
    'x-requested-with',
]

# ==================================================
# CSRF Configuration para API
# ==================================================
CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    default='http://192.168.100.100:3001,http://192.168.100.100,http://localhost:3001'
)

# Eximir API de CSRF (solo para endpoints /api/*)
CSRF_EXEMPT_URLS = [r'^api/']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/uploads')
