"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde backend/.env si existe
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-u7*jsa)d!to@r13ni5y_^5m!kkzy)vhh=xc@h%@#l9j8k=etd3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'django_filters',
    'corsheaders',
    'authentication',
    'leadership',
    # Local apps
    'core',
    'ai_modules.common',
    'ai_modules.sca.apps.ScaConfig',      # Módulo SCA
    'ai_modules.sie.apps.SieConfig',      # Módulo SIE
    'ai_modules.asb.apps.AsbConfig',      # Módulo ASB
    'ai_modules.spm',                     # Módulo SPM 
    'integration',
    'resources',
    'planning',
    'operations',
    'performance',
    'improvement',
]

# Configuración de integración
ADMIN_APPS_INTEGRATION = {
    'BASE_URL': 'http://127.0.0.1:8000/api/integration',
    'API_KEY': 'isosmart-integration-key-2025',
    'TIMEOUT': 10,
    'CACHE_TTL': 300,
    'SYNC_USERS': True,
}

# Patrones de URL por módulo
MODULE_URL_PATTERNS = {
    'SCA': [r'^/api/sca/'],
    'SIE': [r'^/api/sie/', r'^/api/stakeholders/'],
    'ASB': [r'^/api/scope/'],
    'SPM': [r'^/api/processes/'],
    'DOC': [r'^/api/documents/'],
    'RISK': [r'^/api/risks/'],
    'OBJ': [r'^/api/objectives/'],
    'LEAD': [r'^/api/leadership/'],
}

# Comercializacion de estandares ISO:
# - Fase inicial: solo ISO9001_2015
# - Para habilitar nuevas normas por organizacion, usar COMMERCIAL_ENABLED_STANDARDS_BY_ORG
COMMERCIAL_ENABLED_STANDARDS = ['ISO9001_2015']
COMMERCIAL_ENABLED_STANDARDS_BY_ORG = {
    # Ejemplo futuro:
    # 3: ['ISO9001_2015', 'ISO27001_2022'],
}

# Configuración de REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Permitir acceso anónimo por defecto
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT authentication
        'rest_framework.authentication.SessionAuthentication',  # Session authentication para desarrollo
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'backend.middleware.CsrfExemptAPIMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.OrganizationMiddleware',
    'integration.middleware.ModuleAccessMiddleware',
    'integration.middleware.AdminAppsSyncMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'isosmart_main',
        'USER': 'isosmart',
        'PASSWORD': '1s05M4rtNeuraxis',  # Usa tu password
        'HOST': '192.168.100.105',  # IP del servidor de BD
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        }
    },
    # Bases adicionales para IA y auditoría
    'ai_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'isosmart_ai',
        'USER': 'isosmart',
        'PASSWORD': '1s05M4rtNeuraxis',
        'HOST': '192.168.100.105',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },
    'audit_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'isosmart_audit',
        'USER': 'isosmart',
        'PASSWORD': '1s05M4rtNeuraxis',
        'HOST': '192.168.100.105',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}

#Configurar modelo de usuario
AUTH_USER_MODEL = 'authentication.User'

#Configurar backends de autenticación
AUTHENTICATION_BACKENDS = [
    'integration.backends.AdminAppsAuthBackend',  # AdminApps integration auth
    'authentication.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

#Configurar JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Configuración de asistente IA (streaming endpoint)
AI_ASSISTANT_API_URL = os.getenv('AI_ASSISTANT_API_URL', 'https://api.openai.com/v1/chat/completions')
AI_ASSISTANT_API_KEY = os.getenv('AI_ASSISTANT_API_KEY', '')
AI_ASSISTANT_MODEL = os.getenv('AI_ASSISTANT_MODEL', 'gpt-4o-mini')
AI_ASSISTANT_SUPPORTED_STANDARDS = os.getenv(
    'AI_ASSISTANT_SUPPORTED_STANDARDS',
    'ISO 9001, ISO 14001, ISO 45001, ISO 27001, ISO 42001'
)
AI_ASSISTANT_SYSTEM_PROMPT = os.getenv(
    'AI_ASSISTANT_SYSTEM_PROMPT',
    (
        'Eres el asistente virtual de ISO Smart. Responde en español de forma breve, precisa y accionable. '
        'Tu foco principal es orientar sobre sistemas de gestion, clausulas, evidencias, registros, riesgos, '
        'auditorias, no conformidades, acciones correctivas e implementacion por etapas. '
        'Normas prioritarias soportadas: {standards}. '
        'Si la consulta menciona una norma, responde alineado a esa norma. Si no la menciona, prioriza ISO 9001 '
        'como base y aclara cuando una recomendacion depende de la norma aplicable. '
        'No inventes requisitos normativos. Si falta contexto, indicalo y pide la informacion minima necesaria. '
        'Siempre sugiere el siguiente paso practico dentro del modulo actual cuando aplique.'
    ).format(standards=os.getenv(
        'AI_ASSISTANT_SUPPORTED_STANDARDS',
        'ISO 9001, ISO 14001, ISO 45001, ISO 27001, ISO 42001'
    ))
)

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@isosmart.local')
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:5173')
PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = int(os.getenv('PASSWORD_RESET_TOKEN_EXPIRY_MINUTES', '30'))
PASSWORD_RESET_WINDOW_MINUTES = int(os.getenv('PASSWORD_RESET_WINDOW_MINUTES', '60'))
PASSWORD_RESET_MAX_REQUESTS_PER_HOUR = int(os.getenv('PASSWORD_RESET_MAX_REQUESTS_PER_HOUR', '5'))
PASSWORD_HISTORY_COUNT = int(os.getenv('PASSWORD_HISTORY_COUNT', '5'))

# Login brute-force / account-lockout policy
LOGIN_MAX_ATTEMPTS = int(os.getenv('LOGIN_MAX_ATTEMPTS', '5'))
LOGIN_LOCKOUT_MINUTES = int(os.getenv('LOGIN_LOCKOUT_MINUTES', '15'))

# Security headers (enforced by Django SecurityMiddleware)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Configuración de Celery
CELERY_BROKER_URL = 'redis://localhost:6379/1'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Costa_Rica'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'America/Costa_Rica'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales de estáticos
STATICFILES_DIRS = []

# Finder de archivos estáticos
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/home/aplicacion/projects/isosmart/logs/ai/django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://isosmart.local",
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ==================================================
# CSRF Configuration para API
# ==================================================
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.100.100:3001',
    'http://192.168.100.100',
    'http://localhost:3001',
]

# Eximir API de CSRF (solo para endpoints /api/*)
CSRF_EXEMPT_URLS = [r'^api/']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/uploads')