# Generated by Django 4.2.22 on 2026-08-24 23:35

from django.db import migrations, models
import uuid


FORWARD_SQL = r"""
DO $migration$
DECLARE learning_role text := current_setting('foundation.learning_governance_role', true);
BEGIN
  IF learning_role IS NULL OR learning_role='' THEN
    RAISE EXCEPTION 'Phase 21 learning-governance role is required';
  END IF;

  CREATE TABLE qms.learning_signal (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    selected_effectiveness_check_id uuid NOT NULL,
    effectiveness_lineage_id uuid NOT NULL,
    selected_revision integer NOT NULL CHECK(selected_revision>0),
    selected_predecessor_id_snapshot uuid,
    selected_outcome_snapshot varchar(24) NOT NULL,
    selected_was_current_leaf boolean NOT NULL DEFAULT true,
    derivation_timestamp timestamptz NOT NULL,
    derivation_policy_id varchar(120) NOT NULL,
    derivation_policy_version varchar(40) NOT NULL,
    provenance_hash char(64) NOT NULL,
    actor_user_projection_id uuid NOT NULL,
    actor_external_id_snapshot uuid NOT NULL,
    authority_context_version varchar(120) NOT NULL,
    authority_decision_reference varchar(255) NOT NULL,
    trace_id uuid NOT NULL,
    correlation_id uuid,
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_signal_tenant_org_id_unique UNIQUE(tenant_id,organization_id,id),
    CONSTRAINT qms_learning_signal_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_signal_check_fk FOREIGN KEY(tenant_id,organization_id,selected_effectiveness_check_id)
      REFERENCES qms.effectiveness_check(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_signal_actor_fk FOREIGN KEY(tenant_id,actor_user_projection_id)
      REFERENCES qms.user_projection(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_signal_outcome CHECK(selected_outcome_snapshot IN ('effective','ineffective','inconclusive','unknown')),
    CONSTRAINT qms_learning_signal_leaf CHECK(selected_was_current_leaf),
    CONSTRAINT qms_learning_signal_derivation CHECK(
      derivation_policy_id='governed-learning-signal-derivation/v1' AND
      derivation_policy_version='v1' AND btrim(authority_context_version)<>'' AND
      btrim(authority_decision_reference)<>''),
    CONSTRAINT qms_learning_signal_hash CHECK(provenance_hash ~ '^[0-9a-f]{64}$')
  );

  CREATE TABLE qms.learning_signal_effectiveness (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    learning_signal_id uuid NOT NULL,
    effectiveness_check_id uuid NOT NULL,
    lineage_id_snapshot uuid NOT NULL,
    revision_snapshot integer NOT NULL CHECK(revision_snapshot>0),
    predecessor_id_snapshot uuid,
    outcome_snapshot varchar(24) NOT NULL CHECK(outcome_snapshot IN ('effective','ineffective','inconclusive','unknown')),
    check_created_at_snapshot timestamptz NOT NULL,
    is_selected_leaf boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_signal_effectiveness_signal_unique UNIQUE(learning_signal_id,effectiveness_check_id),
    CONSTRAINT qms_learning_signal_effectiveness_revision_unique UNIQUE(learning_signal_id,revision_snapshot),
    CONSTRAINT qms_learning_signal_effectiveness_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_signal_effectiveness_signal_fk FOREIGN KEY(tenant_id,organization_id,learning_signal_id)
      REFERENCES qms.learning_signal(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_signal_effectiveness_check_fk FOREIGN KEY(tenant_id,organization_id,effectiveness_check_id)
      REFERENCES qms.effectiveness_check(tenant_id,organization_id,id) ON DELETE RESTRICT
  );
  CREATE UNIQUE INDEX qms_learning_signal_effectiveness_one_leaf
    ON qms.learning_signal_effectiveness(learning_signal_id) WHERE is_selected_leaf;

  CREATE TABLE qms.learning_proposal (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    target_type varchar(80) NOT NULL,
    target_scope varchar(16) NOT NULL DEFAULT 'global',
    target_id uuid NOT NULL,
    target_lineage_id uuid NOT NULL,
    target_version varchar(120) NOT NULL,
    target_snapshot jsonb NOT NULL,
    target_hash char(64) NOT NULL,
    proposed_change_hash char(64) NOT NULL,
    rationale text NOT NULL,
    expected_effect text NOT NULL,
    risks jsonb NOT NULL DEFAULT '[]'::jsonb,
    required_governance_domains jsonb NOT NULL DEFAULT '[]'::jsonb,
    status varchar(32) NOT NULL DEFAULT 'governance_pending',
    predecessor_id uuid UNIQUE,
    revision integer NOT NULL CHECK(revision>0),
    correction_reason text,
    actor_user_projection_id uuid NOT NULL,
    actor_external_id_snapshot uuid NOT NULL,
    authority_context_version varchar(120) NOT NULL,
    authority_decision_reference varchar(255) NOT NULL,
    policy_id varchar(120) NOT NULL,
    trace_id uuid NOT NULL,
    correlation_id uuid,
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_proposal_tenant_org_id_unique UNIQUE(tenant_id,organization_id,id),
    CONSTRAINT qms_learning_proposal_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_proposal_actor_fk FOREIGN KEY(tenant_id,actor_user_projection_id)
      REFERENCES qms.user_projection(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_proposal_predecessor_fk FOREIGN KEY(tenant_id,organization_id,predecessor_id)
      REFERENCES qms.learning_proposal(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_proposal_target CHECK(target_type IN ('ModelPolicy','AgentDefinition','KnowledgeLayerRule')),
    CONSTRAINT qms_learning_proposal_scope CHECK(target_scope='global'),
    CONSTRAINT qms_learning_proposal_status CHECK(status='governance_pending'),
    CONSTRAINT qms_learning_proposal_policy CHECK(policy_id='governed-learning-implementation-authorization/v1'),
    CONSTRAINT qms_learning_proposal_hashes CHECK(target_hash ~ '^[0-9a-f]{64}$' AND proposed_change_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT qms_learning_proposal_json CHECK(jsonb_typeof(target_snapshot)='object' AND jsonb_typeof(risks)='array' AND jsonb_typeof(required_governance_domains)='array'),
    CONSTRAINT qms_learning_proposal_nonblank CHECK(btrim(target_version)<>'' AND btrim(rationale)<>'' AND btrim(expected_effect)<>'' AND btrim(authority_context_version)<>'' AND btrim(authority_decision_reference)<>''),
    CONSTRAINT qms_learning_proposal_revision CHECK(
      (predecessor_id IS NULL AND revision=1 AND correction_reason IS NULL) OR
      (predecessor_id IS NOT NULL AND revision>1 AND correction_reason IS NOT NULL AND btrim(correction_reason)<>''))
  );

  CREATE TABLE qms.learning_proposal_signal (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    learning_proposal_id uuid NOT NULL,
    learning_signal_id uuid NOT NULL,
    effectiveness_lineage_id_snapshot uuid NOT NULL,
    signal_provenance_hash_snapshot char(64) NOT NULL CHECK(signal_provenance_hash_snapshot ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_proposal_signal_unique UNIQUE(learning_proposal_id,learning_signal_id),
    CONSTRAINT qms_learning_proposal_lineage_unique UNIQUE(learning_proposal_id,effectiveness_lineage_id_snapshot),
    CONSTRAINT qms_learning_proposal_signal_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_proposal_signal_proposal_fk FOREIGN KEY(tenant_id,organization_id,learning_proposal_id)
      REFERENCES qms.learning_proposal(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_proposal_signal_signal_fk FOREIGN KEY(tenant_id,organization_id,learning_signal_id)
      REFERENCES qms.learning_signal(tenant_id,organization_id,id) ON DELETE RESTRICT
  );

  CREATE INDEX qms_learning_signal_lineage_idx ON qms.learning_signal(tenant_id,organization_id,effectiveness_lineage_id,derivation_timestamp);
  CREATE INDEX qms_learning_proposal_target_idx ON qms.learning_proposal(tenant_id,organization_id,target_type,target_id,revision);

  CREATE FUNCTION qms.foundation_0018_reject_learning_mutation()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  BEGIN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='governed learning history is immutable'; END $fn$;

  CREATE FUNCTION qms.foundation_0018_validate_signal()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  DECLARE c record; u record;
  BEGIN
    IF NEW.tenant_id IS DISTINCT FROM NULLIF(current_setting('app.tenant_id',true),'')::uuid OR
       NEW.organization_id IS DISTINCT FROM NULLIF(current_setting('app.organization_id',true),'')::uuid OR
       NEW.actor_external_id_snapshot::text IS DISTINCT FROM current_setting('app.actor_id',true) OR
       current_setting('app.mfa_verified',true)<>'true' OR current_setting('app.access_active',true)<>'true' OR
       position('qms.learning_signal.create' in current_setting('app.learning_permissions',true))=0 OR
       NEW.authority_context_version IS DISTINCT FROM current_setting('app.authority_context_version',true) OR
       NEW.authority_decision_reference IS DISTINCT FROM current_setting('app.authority_decision_reference',true) THEN
      RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='trusted learning-governance signal authority required';
    END IF;
    SELECT * INTO c FROM qms.effectiveness_check WHERE id=NEW.selected_effectiveness_check_id;
    SELECT * INTO u FROM qms.user_projection WHERE id=NEW.actor_user_projection_id;
    IF c.id IS NULL OR u.id IS NULL OR c.action_execution_id IS DISTINCT FROM NEW.effectiveness_lineage_id OR
       c.revision IS DISTINCT FROM NEW.selected_revision OR c.predecessor_id IS DISTINCT FROM NEW.selected_predecessor_id_snapshot OR
       c.outcome IS DISTINCT FROM NEW.selected_outcome_snapshot OR c.created_at>NEW.derivation_timestamp OR
       u.adminapps_user_id IS DISTINCT FROM NEW.actor_external_id_snapshot OR
       EXISTS(SELECT 1 FROM qms.effectiveness_check WHERE predecessor_id=c.id) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningSignal requires the exact authorized current Effectiveness leaf';
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE FUNCTION qms.foundation_0018_validate_signal_effectiveness()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  DECLARE c record; s record;
  BEGIN
    SELECT * INTO c FROM qms.effectiveness_check WHERE id=NEW.effectiveness_check_id;
    SELECT * INTO s FROM qms.learning_signal WHERE id=NEW.learning_signal_id;
    IF c.id IS NULL OR s.id IS NULL OR c.action_execution_id IS DISTINCT FROM NEW.lineage_id_snapshot OR
       s.effectiveness_lineage_id IS DISTINCT FROM NEW.lineage_id_snapshot OR c.revision IS DISTINCT FROM NEW.revision_snapshot OR
       c.predecessor_id IS DISTINCT FROM NEW.predecessor_id_snapshot OR c.outcome IS DISTINCT FROM NEW.outcome_snapshot OR
       c.created_at IS DISTINCT FROM NEW.check_created_at_snapshot OR
       NEW.is_selected_leaf IS DISTINCT FROM (c.id=s.selected_effectiveness_check_id) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningSignalEffectiveness snapshot mismatch';
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE FUNCTION qms.foundation_0018_require_complete_lineage()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  BEGIN
    IF (SELECT count(*) FROM qms.learning_signal_effectiveness WHERE learning_signal_id=NEW.id)<>NEW.selected_revision OR
       (SELECT count(*) FROM qms.learning_signal_effectiveness WHERE learning_signal_id=NEW.id AND is_selected_leaf)<>1 OR
       EXISTS(SELECT 1 FROM generate_series(1,NEW.selected_revision) r
         WHERE NOT EXISTS(SELECT 1 FROM qms.learning_signal_effectiveness e WHERE e.learning_signal_id=NEW.id AND e.revision_snapshot=r)) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningSignal requires a complete frozen Effectiveness lineage';
    END IF;
    RETURN NULL;
  END $fn$;

  CREATE FUNCTION qms.foundation_0018_validate_proposal()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms,governance,normative AS $fn$
  DECLARE target jsonb; prior record; u record;
  BEGIN
    IF NEW.tenant_id IS DISTINCT FROM NULLIF(current_setting('app.tenant_id',true),'')::uuid OR
       NEW.organization_id IS DISTINCT FROM NULLIF(current_setting('app.organization_id',true),'')::uuid OR
       NEW.actor_external_id_snapshot::text IS DISTINCT FROM current_setting('app.actor_id',true) OR
       current_setting('app.mfa_verified',true)<>'true' OR current_setting('app.access_active',true)<>'true' OR
       position('qms.learning_proposal.create' in current_setting('app.learning_permissions',true))=0 OR
       NEW.authority_context_version IS DISTINCT FROM current_setting('app.authority_context_version',true) OR
       NEW.authority_decision_reference IS DISTINCT FROM current_setting('app.authority_decision_reference',true) THEN
      RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='trusted learning-governance proposal authority required';
    END IF;
    IF NEW.target_type='ModelPolicy' THEN
      SELECT to_jsonb(t) INTO target FROM governance.model_policy t WHERE id=NEW.target_id AND lineage_id=NEW.target_lineage_id AND version=NEW.target_version AND status='published' AND NOT EXISTS(SELECT 1 FROM governance.model_policy n WHERE n.previous_revision_id=t.id);
    ELSIF NEW.target_type='AgentDefinition' THEN
      SELECT to_jsonb(t) INTO target FROM governance.agent_definition t WHERE id=NEW.target_id AND lineage_id=NEW.target_lineage_id AND version=NEW.target_version AND status='published' AND NOT EXISTS(SELECT 1 FROM governance.agent_definition n WHERE n.previous_revision_id=t.id);
    ELSIF NEW.target_type='KnowledgeLayerRule' THEN
      SELECT to_jsonb(t) INTO target FROM normative.knowledge_layer_rule t WHERE id=NEW.target_id AND lineage_id=NEW.target_lineage_id AND version=NEW.target_version AND status='published' AND NOT EXISTS(SELECT 1 FROM normative.knowledge_layer_rule n WHERE n.previous_revision_id=t.id);
    END IF;
    SELECT * INTO u FROM qms.user_projection WHERE id=NEW.actor_user_projection_id;
    IF target IS NULL THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningProposal target is stale or not a published current leaf';
    END IF;
    IF target IS DISTINCT FROM NEW.target_snapshot THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningProposal target snapshot is stale or not exact';
    END IF;
    IF u.id IS NULL OR u.adminapps_user_id IS DISTINCT FROM NEW.actor_external_id_snapshot THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningProposal actor snapshot is not exact';
    END IF;
    IF NEW.predecessor_id IS NOT NULL THEN
      SELECT * INTO prior FROM qms.learning_proposal WHERE id=NEW.predecessor_id;
      IF prior.id IS NULL OR NEW.revision<>prior.revision+1 OR NEW.target_type<>prior.target_type OR
         NEW.target_id<>prior.target_id OR NEW.target_hash<>prior.target_hash OR
         EXISTS(SELECT 1 FROM qms.learning_proposal WHERE predecessor_id=prior.id) THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningProposal history must be exact and linear';
      END IF;
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE FUNCTION qms.foundation_0018_validate_proposal_signal()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  DECLARE s record; p record;
  BEGIN
    SELECT * INTO s FROM qms.learning_signal WHERE id=NEW.learning_signal_id;
    SELECT * INTO p FROM qms.learning_proposal WHERE id=NEW.learning_proposal_id;
    IF s.id IS NULL OR p.id IS NULL OR s.tenant_id<>p.tenant_id OR s.organization_id<>p.organization_id OR
       s.effectiveness_lineage_id<>NEW.effectiveness_lineage_id_snapshot OR
       s.provenance_hash<>NEW.signal_provenance_hash_snapshot THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningProposalSignal exact provenance mismatch';
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE FUNCTION qms.foundation_0018_require_proposal_signal()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  BEGIN
    IF NOT EXISTS(SELECT 1 FROM qms.learning_proposal_signal WHERE learning_proposal_id=NEW.id) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='LearningProposal requires exact supporting signals';
    END IF;
    RETURN NULL;
  END $fn$;

  CREATE TRIGGER qms_learning_signal_validate BEFORE INSERT ON qms.learning_signal FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_validate_signal();
  CREATE TRIGGER qms_learning_signal_guard BEFORE UPDATE OR DELETE ON qms.learning_signal FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_reject_learning_mutation();
  CREATE TRIGGER qms_learning_signal_effectiveness_validate BEFORE INSERT ON qms.learning_signal_effectiveness FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_validate_signal_effectiveness();
  CREATE TRIGGER qms_learning_signal_effectiveness_guard BEFORE UPDATE OR DELETE ON qms.learning_signal_effectiveness FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_reject_learning_mutation();
  CREATE CONSTRAINT TRIGGER qms_learning_signal_lineage_required AFTER INSERT ON qms.learning_signal DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_require_complete_lineage();
  CREATE TRIGGER qms_learning_proposal_validate BEFORE INSERT ON qms.learning_proposal FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_validate_proposal();
  CREATE TRIGGER qms_learning_proposal_guard BEFORE UPDATE OR DELETE ON qms.learning_proposal FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_reject_learning_mutation();
  CREATE TRIGGER qms_learning_proposal_signal_validate BEFORE INSERT ON qms.learning_proposal_signal FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_validate_proposal_signal();
  CREATE TRIGGER qms_learning_proposal_signal_guard BEFORE UPDATE OR DELETE ON qms.learning_proposal_signal FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_reject_learning_mutation();
  CREATE CONSTRAINT TRIGGER qms_learning_proposal_signal_required AFTER INSERT ON qms.learning_proposal DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION qms.foundation_0018_require_proposal_signal();

  ALTER TABLE qms.learning_signal ENABLE ROW LEVEL SECURITY; ALTER TABLE qms.learning_signal FORCE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_signal_effectiveness ENABLE ROW LEVEL SECURITY; ALTER TABLE qms.learning_signal_effectiveness FORCE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_proposal ENABLE ROW LEVEL SECURITY; ALTER TABLE qms.learning_proposal FORCE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_proposal_signal ENABLE ROW LEVEL SECURITY; ALTER TABLE qms.learning_proposal_signal FORCE ROW LEVEL SECURITY;
  EXECUTE format('CREATE POLICY qms_learning_signal_select ON qms.learning_signal FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_signal_insert ON qms.learning_signal FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_signal_effectiveness_select ON qms.learning_signal_effectiveness FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_signal_effectiveness_insert ON qms.learning_signal_effectiveness FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_proposal_select ON qms.learning_proposal FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_proposal_insert ON qms.learning_proposal FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_proposal_signal_select ON qms.learning_proposal_signal FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_proposal_signal_insert ON qms.learning_proposal_signal FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_learning_signal_migrator ON qms.learning_signal FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);
  EXECUTE format('CREATE POLICY qms_learning_signal_effectiveness_migrator ON qms.learning_signal_effectiveness FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);
  EXECUTE format('CREATE POLICY qms_learning_proposal_migrator ON qms.learning_proposal FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);
  EXECUTE format('CREATE POLICY qms_learning_proposal_signal_migrator ON qms.learning_proposal_signal FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);

  EXECUTE format('CREATE POLICY qms_effectiveness_learning_select ON qms.effectiveness_check FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_organization_learning_select ON qms.organization FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY qms_user_projection_learning_select ON qms.user_projection FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY eventing_learning_event_select ON eventing.domain_event FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY eventing_learning_event_insert ON eventing.domain_event FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY eventing_learning_outbox_select ON eventing.transactional_outbox FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('CREATE POLICY eventing_learning_outbox_insert ON eventing.transactional_outbox FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',learning_role);
  EXECUTE format('GRANT SELECT,INSERT ON qms.learning_signal,qms.learning_signal_effectiveness,qms.learning_proposal,qms.learning_proposal_signal TO %I',learning_role);
  EXECUTE format('GRANT USAGE ON SCHEMA qms,eventing,audit,governance,normative TO %I',learning_role);
  EXECUTE format('GRANT SELECT ON qms.organization,qms.user_projection,qms.effectiveness_check,governance.model_policy,governance.agent_definition,normative.knowledge_layer_rule TO %I',learning_role);
  EXECUTE format('GRANT SELECT,INSERT ON eventing.domain_event,eventing.transactional_outbox TO %I',learning_role);
  EXECUTE format('GRANT EXECUTE ON FUNCTION audit.append_immutable_audit(uuid,text,uuid,text,text,text,text,uuid,uuid,timestamptz,text,text,text) TO %I',learning_role);
END $migration$;
"""


REVERSE_SQL = r"""
DO $migration$ BEGIN
  IF EXISTS(SELECT 1 FROM qms.learning_signal) OR EXISTS(SELECT 1 FROM qms.learning_proposal) THEN
    RAISE EXCEPTION '0018 is forward-only after governed learning history exists';
  END IF;
END $migration$;
DO $migration$
DECLARE learning_role text := current_setting('foundation.learning_governance_role', true);
BEGIN
  DROP POLICY qms_effectiveness_learning_select ON qms.effectiveness_check;
  DROP POLICY qms_organization_learning_select ON qms.organization;
  DROP POLICY qms_user_projection_learning_select ON qms.user_projection;
  DROP POLICY eventing_learning_event_select ON eventing.domain_event;
  DROP POLICY eventing_learning_event_insert ON eventing.domain_event;
  DROP POLICY eventing_learning_outbox_select ON eventing.transactional_outbox;
  DROP POLICY eventing_learning_outbox_insert ON eventing.transactional_outbox;
  EXECUTE format('REVOKE SELECT ON qms.organization,qms.user_projection,qms.effectiveness_check,governance.model_policy,governance.agent_definition,normative.knowledge_layer_rule FROM %I',learning_role);
  EXECUTE format('REVOKE SELECT,INSERT ON eventing.domain_event,eventing.transactional_outbox FROM %I',learning_role);
  EXECUTE format('REVOKE EXECUTE ON FUNCTION audit.append_immutable_audit(uuid,text,uuid,text,text,text,text,uuid,uuid,timestamptz,text,text,text) FROM %I',learning_role);
  EXECUTE format('REVOKE USAGE ON SCHEMA qms,eventing,audit,governance,normative FROM %I',learning_role);
END $migration$;
DROP TABLE qms.learning_proposal_signal; DROP TABLE qms.learning_proposal;
DROP TABLE qms.learning_signal_effectiveness; DROP TABLE qms.learning_signal;
DROP FUNCTION qms.foundation_0018_require_proposal_signal(); DROP FUNCTION qms.foundation_0018_validate_proposal_signal();
DROP FUNCTION qms.foundation_0018_validate_proposal(); DROP FUNCTION qms.foundation_0018_require_complete_lineage();
DROP FUNCTION qms.foundation_0018_validate_signal_effectiveness(); DROP FUNCTION qms.foundation_0018_validate_signal();
DROP FUNCTION qms.foundation_0018_reject_learning_mutation();
"""


def apply_phase21(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL, params=None)


def reverse_phase21(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0017_effectiveness_check_foundation'),
    ]

    operations = [
        migrations.RunPython(apply_phase21, reverse_phase21),
        migrations.CreateModel(
            name='LearningProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=80)),
                ('target_scope', models.CharField(default='global', max_length=16)),
                ('target_id', models.UUIDField()),
                ('target_lineage_id', models.UUIDField()),
                ('target_version', models.CharField(max_length=120)),
                ('target_snapshot', models.JSONField()),
                ('target_hash', models.CharField(max_length=64)),
                ('proposed_change_hash', models.CharField(max_length=64)),
                ('rationale', models.TextField()),
                ('expected_effect', models.TextField()),
                ('risks', models.JSONField(default=list)),
                ('required_governance_domains', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('governance_pending', 'Governance pending')], default='governance_pending', max_length=32)),
                ('revision', models.PositiveIntegerField()),
                ('correction_reason', models.TextField(blank=True, null=True)),
                ('actor_external_id_snapshot', models.UUIDField()),
                ('authority_context_version', models.CharField(max_length=120)),
                ('authority_decision_reference', models.CharField(max_length=255)),
                ('policy_id', models.CharField(max_length=120)),
                ('trace_id', models.UUIDField()),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qms"."learning_proposal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningProposalSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effectiveness_lineage_id_snapshot', models.UUIDField()),
                ('signal_provenance_hash_snapshot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qms"."learning_proposal_signal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effectiveness_lineage_id', models.UUIDField()),
                ('selected_revision', models.PositiveIntegerField()),
                ('selected_predecessor_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('selected_outcome_snapshot', models.CharField(choices=[('effective', 'Effective'), ('ineffective', 'Ineffective'), ('inconclusive', 'Inconclusive'), ('unknown', 'Unknown')], max_length=24)),
                ('selected_was_current_leaf', models.BooleanField(default=True)),
                ('derivation_timestamp', models.DateTimeField()),
                ('derivation_policy_id', models.CharField(max_length=120)),
                ('derivation_policy_version', models.CharField(max_length=40)),
                ('provenance_hash', models.CharField(max_length=64)),
                ('actor_external_id_snapshot', models.UUIDField()),
                ('authority_context_version', models.CharField(max_length=120)),
                ('authority_decision_reference', models.CharField(max_length=255)),
                ('trace_id', models.UUIDField()),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qms"."learning_signal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningSignalEffectiveness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lineage_id_snapshot', models.UUIDField()),
                ('revision_snapshot', models.PositiveIntegerField()),
                ('predecessor_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('outcome_snapshot', models.CharField(choices=[('effective', 'Effective'), ('ineffective', 'Ineffective'), ('inconclusive', 'Inconclusive'), ('unknown', 'Unknown')], max_length=24)),
                ('check_created_at_snapshot', models.DateTimeField()),
                ('is_selected_leaf', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qms"."learning_signal_effectiveness',
                'managed': False,
            },
        ),
    ]
