# Generated by Django 4.2.22 on 2026-08-25

from django.db import migrations, models
import django.db.models.deletion
import uuid


FORWARD_SQL = r"""
DO $migration$
DECLARE
  reviewer_role text := current_setting('foundation.learning_reviewer_role',true);
  approver_role text := current_setting('foundation.learning_approver_role',true);
  authorizer_role text := current_setting('foundation.learning_authorizer_role',true);
BEGIN
  IF reviewer_role IS NULL OR reviewer_role='' OR approver_role IS NULL OR approver_role='' OR
     authorizer_role IS NULL OR authorizer_role='' OR
     reviewer_role=approver_role OR reviewer_role=authorizer_role OR approver_role=authorizer_role THEN
    RAISE EXCEPTION 'Phase 23 requires three separate governance principals';
  END IF;

  CREATE TABLE qms.learning_proposal_review (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    learning_proposal_id uuid NOT NULL,
    proposal_revision_snapshot integer NOT NULL CHECK(proposal_revision_snapshot>0),
    proposal_predecessor_id_snapshot uuid,
    proposal_material_hash char(64) NOT NULL CHECK(proposal_material_hash ~ '^[0-9a-f]{64}$'),
    target_type varchar(80) NOT NULL,
    target_id uuid NOT NULL,
    target_lineage_id uuid NOT NULL,
    target_version varchar(120) NOT NULL,
    target_hash char(64) NOT NULL CHECK(target_hash ~ '^[0-9a-f]{64}$'),
    target_status_snapshot varchar(16) NOT NULL CHECK(target_status_snapshot IN ('valid','stale')),
    review_outcome varchar(32) NOT NULL DEFAULT 'review_recorded' CHECK(review_outcome='review_recorded'),
    findings jsonb NOT NULL,
    reviewed_governance_domains jsonb NOT NULL,
    reviewer_user_projection_id uuid NOT NULL,
    reviewer_external_id_snapshot uuid NOT NULL,
    authority_context_version varchar(120) NOT NULL,
    authority_decision_reference varchar(255) NOT NULL,
    governance_scope varchar(16) NOT NULL DEFAULT 'global' CHECK(governance_scope='global'),
    policy_id varchar(160) NOT NULL CHECK(policy_id='governed-learning-proposal-review-application-boundary/v1'),
    trace_id uuid NOT NULL,
    correlation_id uuid,
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_review_tenant_org_id_unique UNIQUE(tenant_id,organization_id,id),
    CONSTRAINT qms_learning_review_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_review_proposal_fk FOREIGN KEY(tenant_id,organization_id,learning_proposal_id)
      REFERENCES qms.learning_proposal(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_review_actor_fk FOREIGN KEY(tenant_id,reviewer_user_projection_id)
      REFERENCES qms.user_projection(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_review_json CHECK(
      jsonb_typeof(findings)='object' AND jsonb_typeof(reviewed_governance_domains)='array' AND
      jsonb_array_length(reviewed_governance_domains)>0),
    CONSTRAINT qms_learning_review_nonblank CHECK(
      btrim(target_version)<>'' AND btrim(authority_context_version)<>'' AND
      btrim(authority_decision_reference)<>'')
  );

  CREATE TABLE qms.learning_proposal_decision (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    learning_proposal_id uuid NOT NULL UNIQUE,
    proposal_revision_snapshot integer NOT NULL CHECK(proposal_revision_snapshot>0),
    proposal_predecessor_id_snapshot uuid,
    proposal_material_hash char(64) NOT NULL CHECK(proposal_material_hash ~ '^[0-9a-f]{64}$'),
    review_ids_snapshot jsonb NOT NULL,
    review_set_hash char(64) NOT NULL CHECK(review_set_hash ~ '^[0-9a-f]{64}$'),
    target_type varchar(80) NOT NULL,
    target_id uuid NOT NULL,
    target_lineage_id uuid NOT NULL,
    target_version varchar(120) NOT NULL,
    target_hash char(64) NOT NULL CHECK(target_hash ~ '^[0-9a-f]{64}$'),
    outcome varchar(32) NOT NULL CHECK(outcome IN ('approved_for_application','rejected','changes_requested')),
    rationale text NOT NULL,
    decision_identity_hash char(64) NOT NULL UNIQUE CHECK(decision_identity_hash ~ '^[0-9a-f]{64}$'),
    approver_user_projection_id uuid NOT NULL,
    approver_external_id_snapshot uuid NOT NULL,
    authority_context_version varchar(120) NOT NULL,
    authority_decision_reference varchar(255) NOT NULL,
    governance_scope varchar(16) NOT NULL DEFAULT 'global' CHECK(governance_scope='global'),
    policy_id varchar(160) NOT NULL CHECK(policy_id='governed-learning-proposal-review-application-boundary/v1'),
    trace_id uuid NOT NULL,
    correlation_id uuid,
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_decision_tenant_org_id_unique UNIQUE(tenant_id,organization_id,id),
    CONSTRAINT qms_learning_decision_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_decision_proposal_fk FOREIGN KEY(tenant_id,organization_id,learning_proposal_id)
      REFERENCES qms.learning_proposal(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_decision_actor_fk FOREIGN KEY(tenant_id,approver_user_projection_id)
      REFERENCES qms.user_projection(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_decision_reviews CHECK(
      jsonb_typeof(review_ids_snapshot)='array' AND jsonb_array_length(review_ids_snapshot)>0),
    CONSTRAINT qms_learning_decision_nonblank CHECK(
      btrim(target_version)<>'' AND btrim(rationale)<>'' AND btrim(authority_context_version)<>'' AND
      btrim(authority_decision_reference)<>'')
  );

  CREATE TABLE qms.learning_application_authorization (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES qms.tenant_projection(id) ON DELETE RESTRICT,
    organization_id uuid NOT NULL,
    learning_proposal_id uuid NOT NULL,
    learning_proposal_decision_id uuid NOT NULL UNIQUE,
    proposal_revision_snapshot integer NOT NULL CHECK(proposal_revision_snapshot>0),
    proposal_material_hash char(64) NOT NULL CHECK(proposal_material_hash ~ '^[0-9a-f]{64}$'),
    target_type varchar(80) NOT NULL,
    target_id uuid NOT NULL,
    target_lineage_id uuid NOT NULL,
    target_version varchar(120) NOT NULL,
    target_hash char(64) NOT NULL CHECK(target_hash ~ '^[0-9a-f]{64}$'),
    capability_id varchar(160) NOT NULL,
    capability_version varchar(40) NOT NULL DEFAULT 'v1' CHECK(capability_version='v1'),
    authorization_status varchar(24) NOT NULL DEFAULT 'authorized' CHECK(authorization_status='authorized'),
    idempotency_key varchar(255) NOT NULL,
    idempotency_hash char(64) NOT NULL CHECK(idempotency_hash ~ '^[0-9a-f]{64}$'),
    authorizer_user_projection_id uuid NOT NULL,
    authorizer_external_id_snapshot uuid NOT NULL,
    authority_context_version varchar(120) NOT NULL,
    authority_decision_reference varchar(255) NOT NULL,
    governance_scope varchar(16) NOT NULL DEFAULT 'global' CHECK(governance_scope='global'),
    policy_id varchar(160) NOT NULL CHECK(policy_id='governed-learning-proposal-review-application-boundary/v1'),
    trace_id uuid NOT NULL,
    correlation_id uuid,
    created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT qms_learning_authorization_tenant_org_id_unique UNIQUE(tenant_id,organization_id,id),
    CONSTRAINT qms_learning_authorization_idempotency_unique UNIQUE(tenant_id,idempotency_key),
    CONSTRAINT qms_learning_authorization_org_fk FOREIGN KEY(tenant_id,organization_id)
      REFERENCES qms.organization(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_authorization_proposal_fk FOREIGN KEY(tenant_id,organization_id,learning_proposal_id)
      REFERENCES qms.learning_proposal(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_authorization_decision_fk FOREIGN KEY(tenant_id,organization_id,learning_proposal_decision_id)
      REFERENCES qms.learning_proposal_decision(tenant_id,organization_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_authorization_actor_fk FOREIGN KEY(tenant_id,authorizer_user_projection_id)
      REFERENCES qms.user_projection(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT qms_learning_authorization_capability CHECK(
      (target_type='ModelPolicy' AND capability_id='revise_model_policy') OR
      (target_type='AgentDefinition' AND capability_id='revise_agent_definition') OR
      (target_type='KnowledgeLayerRule' AND capability_id='revise_knowledge_layer_rule')),
    CONSTRAINT qms_learning_authorization_nonblank CHECK(
      btrim(target_version)<>'' AND btrim(idempotency_key)<>'' AND
      btrim(authority_context_version)<>'' AND btrim(authority_decision_reference)<>'')
  );

  CREATE INDEX qms_learning_review_proposal_idx
    ON qms.learning_proposal_review(tenant_id,organization_id,learning_proposal_id,created_at);
  CREATE INDEX qms_learning_decision_target_idx
    ON qms.learning_proposal_decision(tenant_id,organization_id,target_type,target_id,target_version);
  CREATE INDEX qms_learning_authorization_target_idx
    ON qms.learning_application_authorization(tenant_id,organization_id,target_type,target_id,target_version);

  CREATE FUNCTION qms.foundation_0019_reject_governance_mutation()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms AS $fn$
  BEGIN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='Phase 23 governance history is immutable'; END $fn$;

  CREATE FUNCTION qms.foundation_0019_current_target(p_type text,p_id uuid,p_lineage uuid,p_version text)
  RETURNS jsonb LANGUAGE plpgsql STABLE SET search_path=pg_catalog,governance,normative AS $fn$
  DECLARE target jsonb;
  BEGIN
    IF p_type='ModelPolicy' THEN
      SELECT to_jsonb(t) INTO target FROM governance.model_policy t WHERE id=p_id AND lineage_id=p_lineage AND version=p_version AND status='published' AND NOT EXISTS(SELECT 1 FROM governance.model_policy n WHERE n.previous_revision_id=t.id);
    ELSIF p_type='AgentDefinition' THEN
      SELECT to_jsonb(t) INTO target FROM governance.agent_definition t WHERE id=p_id AND lineage_id=p_lineage AND version=p_version AND status='published' AND NOT EXISTS(SELECT 1 FROM governance.agent_definition n WHERE n.previous_revision_id=t.id);
    ELSIF p_type='KnowledgeLayerRule' THEN
      SELECT to_jsonb(t) INTO target FROM normative.knowledge_layer_rule t WHERE id=p_id AND lineage_id=p_lineage AND version=p_version AND status='published' AND NOT EXISTS(SELECT 1 FROM normative.knowledge_layer_rule n WHERE n.previous_revision_id=t.id);
    END IF;
    RETURN target;
  END $fn$;

  CREATE FUNCTION qms.foundation_0019_validate_review()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms,governance,normative AS $fn$
  DECLARE p record; u record; target jsonb; expected_status text;
  BEGIN
    IF NEW.tenant_id IS DISTINCT FROM NULLIF(current_setting('app.tenant_id',true),'')::uuid OR
       NEW.organization_id IS DISTINCT FROM NULLIF(current_setting('app.organization_id',true),'')::uuid OR
       NEW.reviewer_external_id_snapshot::text IS DISTINCT FROM current_setting('app.actor_id',true) OR
       current_setting('app.governance_actor_type',true)<>'human' OR
       current_setting('app.governance_scope',true)<>'global' OR
       current_setting('app.mfa_verified',true)<>'true' OR current_setting('app.access_active',true)<>'true' OR
       position('qms.learning_proposal.review' in current_setting('app.learning_review_permissions',true))=0 OR
       NEW.authority_context_version IS DISTINCT FROM current_setting('app.authority_context_version',true) OR
       NEW.authority_decision_reference IS DISTINCT FROM current_setting('app.authority_decision_reference',true) THEN
      RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='trusted global learning review authority required';
    END IF;
    SELECT * INTO p FROM qms.learning_proposal WHERE id=NEW.learning_proposal_id;
    SELECT * INTO u FROM qms.user_projection WHERE id=NEW.reviewer_user_projection_id;
    IF p.id IS NULL OR u.id IS NULL OR u.adminapps_user_id IS DISTINCT FROM NEW.reviewer_external_id_snapshot OR
       p.tenant_id<>NEW.tenant_id OR p.organization_id<>NEW.organization_id OR
       p.revision<>NEW.proposal_revision_snapshot OR p.predecessor_id IS DISTINCT FROM NEW.proposal_predecessor_id_snapshot OR
       p.target_type<>NEW.target_type OR p.target_id<>NEW.target_id OR p.target_lineage_id<>NEW.target_lineage_id OR
       p.target_version<>NEW.target_version OR p.target_hash<>NEW.target_hash THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='review does not freeze the exact proposal revision and target';
    END IF;
    target := qms.foundation_0019_current_target(p.target_type,p.target_id,p.target_lineage_id,p.target_version);
    expected_status := CASE WHEN target IS NOT NULL AND target=p.target_snapshot THEN 'valid' ELSE 'stale' END;
    IF NEW.target_status_snapshot<>expected_status THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='review target status snapshot is not exact';
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE FUNCTION qms.foundation_0019_validate_decision()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms,governance,normative AS $fn$
  DECLARE p record; u record; target jsonb; review_count integer;
  BEGIN
    IF NEW.tenant_id IS DISTINCT FROM NULLIF(current_setting('app.tenant_id',true),'')::uuid OR
       NEW.organization_id IS DISTINCT FROM NULLIF(current_setting('app.organization_id',true),'')::uuid OR
       NEW.approver_external_id_snapshot::text IS DISTINCT FROM current_setting('app.actor_id',true) OR
       current_setting('app.governance_actor_type',true)<>'human' OR
       current_setting('app.governance_scope',true)<>'global' OR
       current_setting('app.mfa_verified',true)<>'true' OR current_setting('app.access_active',true)<>'true' OR
       position('qms.learning_proposal.decide' in current_setting('app.learning_decision_permissions',true))=0 OR
       NEW.authority_context_version IS DISTINCT FROM current_setting('app.authority_context_version',true) OR
       NEW.authority_decision_reference IS DISTINCT FROM current_setting('app.authority_decision_reference',true) THEN
      RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='trusted global learning decision authority required';
    END IF;
    SELECT * INTO p FROM qms.learning_proposal WHERE id=NEW.learning_proposal_id;
    SELECT * INTO u FROM qms.user_projection WHERE id=NEW.approver_user_projection_id;
    IF p.id IS NULL OR u.id IS NULL OR u.adminapps_user_id IS DISTINCT FROM NEW.approver_external_id_snapshot OR
       p.actor_external_id_snapshot=NEW.approver_external_id_snapshot OR
       p.tenant_id<>NEW.tenant_id OR p.organization_id<>NEW.organization_id OR
       p.revision<>NEW.proposal_revision_snapshot OR p.predecessor_id IS DISTINCT FROM NEW.proposal_predecessor_id_snapshot OR
       p.target_type<>NEW.target_type OR p.target_id<>NEW.target_id OR p.target_lineage_id<>NEW.target_lineage_id OR
       p.target_version<>NEW.target_version OR p.target_hash<>NEW.target_hash OR
       EXISTS(SELECT 1 FROM qms.learning_proposal n WHERE n.predecessor_id=p.id) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='decision requires exact current proposal and independent approver';
    END IF;
    target := qms.foundation_0019_current_target(p.target_type,p.target_id,p.target_lineage_id,p.target_version);
    IF target IS NULL OR target<>p.target_snapshot THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='target drift prevents proposal decision';
    END IF;
    SELECT count(*) INTO review_count
      FROM jsonb_array_elements_text(NEW.review_ids_snapshot) item
      JOIN qms.learning_proposal_review r ON r.id=item::uuid
      WHERE r.tenant_id=NEW.tenant_id AND r.organization_id=NEW.organization_id AND
            r.learning_proposal_id=NEW.learning_proposal_id AND
            r.proposal_revision_snapshot=NEW.proposal_revision_snapshot AND r.target_status_snapshot='valid';
    IF review_count<>jsonb_array_length(NEW.review_ids_snapshot) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='decision reviews are missing, stale, or from another proposal boundary';
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE FUNCTION qms.foundation_0019_validate_authorization()
  RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,qms,governance,normative AS $fn$
  DECLARE p record; d record; u record; target jsonb;
  BEGIN
    IF NEW.tenant_id IS DISTINCT FROM NULLIF(current_setting('app.tenant_id',true),'')::uuid OR
       NEW.organization_id IS DISTINCT FROM NULLIF(current_setting('app.organization_id',true),'')::uuid OR
       NEW.authorizer_external_id_snapshot::text IS DISTINCT FROM current_setting('app.actor_id',true) OR
       current_setting('app.governance_actor_type',true)<>'human' OR
       current_setting('app.governance_scope',true)<>'global' OR
       current_setting('app.mfa_verified',true)<>'true' OR current_setting('app.access_active',true)<>'true' OR
       position('qms.learning_application.authorize' in current_setting('app.learning_authorization_permissions',true))=0 OR
       NEW.authority_context_version IS DISTINCT FROM current_setting('app.authority_context_version',true) OR
       NEW.authority_decision_reference IS DISTINCT FROM current_setting('app.authority_decision_reference',true) THEN
      RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='trusted global application-authorization authority required';
    END IF;
    SELECT * INTO p FROM qms.learning_proposal WHERE id=NEW.learning_proposal_id;
    SELECT * INTO d FROM qms.learning_proposal_decision WHERE id=NEW.learning_proposal_decision_id;
    SELECT * INTO u FROM qms.user_projection WHERE id=NEW.authorizer_user_projection_id;
    IF p.id IS NULL OR d.id IS NULL OR u.id IS NULL OR u.adminapps_user_id IS DISTINCT FROM NEW.authorizer_external_id_snapshot OR
       p.actor_external_id_snapshot=NEW.authorizer_external_id_snapshot OR d.approver_external_id_snapshot=NEW.authorizer_external_id_snapshot OR
       d.learning_proposal_id<>p.id OR d.outcome<>'approved_for_application' OR
       p.tenant_id<>NEW.tenant_id OR p.organization_id<>NEW.organization_id OR
       p.revision<>NEW.proposal_revision_snapshot OR p.target_type<>NEW.target_type OR
       p.target_id<>NEW.target_id OR p.target_lineage_id<>NEW.target_lineage_id OR
       p.target_version<>NEW.target_version OR p.target_hash<>NEW.target_hash OR
       EXISTS(SELECT 1 FROM qms.learning_proposal n WHERE n.predecessor_id=p.id) THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='authorization requires exact approved current proposal and independent authority';
    END IF;
    target := qms.foundation_0019_current_target(p.target_type,p.target_id,p.target_lineage_id,p.target_version);
    IF target IS NULL OR target<>p.target_snapshot THEN
      RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='target drift prevents application authorization';
    END IF;
    RETURN NEW;
  END $fn$;

  CREATE TRIGGER qms_learning_review_validate BEFORE INSERT ON qms.learning_proposal_review FOR EACH ROW EXECUTE FUNCTION qms.foundation_0019_validate_review();
  CREATE TRIGGER qms_learning_review_guard BEFORE UPDATE OR DELETE ON qms.learning_proposal_review FOR EACH ROW EXECUTE FUNCTION qms.foundation_0019_reject_governance_mutation();
  CREATE TRIGGER qms_learning_decision_validate BEFORE INSERT ON qms.learning_proposal_decision FOR EACH ROW EXECUTE FUNCTION qms.foundation_0019_validate_decision();
  CREATE TRIGGER qms_learning_decision_guard BEFORE UPDATE OR DELETE ON qms.learning_proposal_decision FOR EACH ROW EXECUTE FUNCTION qms.foundation_0019_reject_governance_mutation();
  CREATE TRIGGER qms_learning_authorization_validate BEFORE INSERT ON qms.learning_application_authorization FOR EACH ROW EXECUTE FUNCTION qms.foundation_0019_validate_authorization();
  CREATE TRIGGER qms_learning_authorization_guard BEFORE UPDATE OR DELETE ON qms.learning_application_authorization FOR EACH ROW EXECUTE FUNCTION qms.foundation_0019_reject_governance_mutation();

  ALTER TABLE qms.learning_proposal_review ENABLE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_proposal_review FORCE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_proposal_decision ENABLE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_proposal_decision FORCE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_application_authorization ENABLE ROW LEVEL SECURITY;
  ALTER TABLE qms.learning_application_authorization FORCE ROW LEVEL SECURITY;

  EXECUTE format('CREATE POLICY qms_learning_review_select ON qms.learning_proposal_review FOR SELECT TO %I,%I,%I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('CREATE POLICY qms_learning_review_insert ON qms.learning_proposal_review FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',reviewer_role);
  EXECUTE format('CREATE POLICY qms_learning_decision_select ON qms.learning_proposal_decision FOR SELECT TO %I,%I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',approver_role,authorizer_role);
  EXECUTE format('CREATE POLICY qms_learning_decision_insert ON qms.learning_proposal_decision FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',approver_role);
  EXECUTE format('CREATE POLICY qms_learning_authorization_select ON qms.learning_application_authorization FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',authorizer_role);
  EXECUTE format('CREATE POLICY qms_learning_authorization_insert ON qms.learning_application_authorization FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',authorizer_role);
  EXECUTE format('CREATE POLICY qms_learning_review_migrator ON qms.learning_proposal_review FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);
  EXECUTE format('CREATE POLICY qms_learning_decision_migrator ON qms.learning_proposal_decision FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);
  EXECUTE format('CREATE POLICY qms_learning_authorization_migrator ON qms.learning_application_authorization FOR ALL TO %I USING(true) WITH CHECK(true)',current_user);

  EXECUTE format('CREATE POLICY qms_learning_proposal_reviewer_select ON qms.learning_proposal FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',reviewer_role);
  EXECUTE format('CREATE POLICY qms_learning_proposal_approver_select ON qms.learning_proposal FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',approver_role);
  EXECUTE format('CREATE POLICY qms_learning_proposal_authorizer_select ON qms.learning_proposal FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',authorizer_role);
  EXECUTE format('CREATE POLICY qms_user_reviewer_select ON qms.user_projection FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',reviewer_role);
  EXECUTE format('CREATE POLICY qms_user_approver_select ON qms.user_projection FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',approver_role);
  EXECUTE format('CREATE POLICY qms_user_authorizer_select ON qms.user_projection FOR SELECT TO %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',authorizer_role);

  EXECUTE format('CREATE POLICY eventing_reviewer_event_insert ON eventing.domain_event FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',reviewer_role);
  EXECUTE format('CREATE POLICY eventing_reviewer_outbox_insert ON eventing.transactional_outbox FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',reviewer_role);
  EXECUTE format('CREATE POLICY eventing_approver_event_insert ON eventing.domain_event FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',approver_role);
  EXECUTE format('CREATE POLICY eventing_approver_outbox_insert ON eventing.transactional_outbox FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',approver_role);
  EXECUTE format('CREATE POLICY eventing_authorizer_event_insert ON eventing.domain_event FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',authorizer_role);
  EXECUTE format('CREATE POLICY eventing_authorizer_outbox_insert ON eventing.transactional_outbox FOR INSERT TO %I WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',authorizer_role);

  EXECUTE format('GRANT USAGE ON SCHEMA qms,eventing,audit,governance,normative TO %I,%I,%I',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('GRANT SELECT ON qms.organization,qms.user_projection,qms.learning_proposal,governance.model_policy,governance.agent_definition,normative.knowledge_layer_rule TO %I,%I,%I',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('GRANT SELECT,INSERT ON qms.learning_proposal_review TO %I',reviewer_role);
  EXECUTE format('GRANT SELECT ON qms.learning_proposal_review TO %I,%I',approver_role,authorizer_role);
  EXECUTE format('GRANT SELECT,INSERT ON qms.learning_proposal_decision TO %I',approver_role);
  EXECUTE format('GRANT SELECT ON qms.learning_proposal_decision TO %I',authorizer_role);
  EXECUTE format('GRANT SELECT,INSERT ON qms.learning_application_authorization TO %I',authorizer_role);
  EXECUTE format('GRANT INSERT ON eventing.domain_event,eventing.transactional_outbox TO %I,%I,%I',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('GRANT EXECUTE ON FUNCTION audit.append_immutable_audit(uuid,text,uuid,text,text,text,text,uuid,uuid,timestamptz,text,text,text) TO %I,%I,%I',reviewer_role,approver_role,authorizer_role);
END $migration$;
"""


REVERSE_SQL = r"""
DO $migration$ BEGIN
  IF EXISTS(SELECT 1 FROM qms.learning_proposal_review) OR
     EXISTS(SELECT 1 FROM qms.learning_proposal_decision) OR
     EXISTS(SELECT 1 FROM qms.learning_application_authorization) THEN
    RAISE EXCEPTION '0019 is forward-only after retained Phase 23 governance history exists';
  END IF;
END $migration$;
DO $migration$
DECLARE
  reviewer_role text := current_setting('foundation.learning_reviewer_role',true);
  approver_role text := current_setting('foundation.learning_approver_role',true);
  authorizer_role text := current_setting('foundation.learning_authorizer_role',true);
BEGIN
  DROP POLICY eventing_reviewer_event_insert ON eventing.domain_event;
  DROP POLICY eventing_reviewer_outbox_insert ON eventing.transactional_outbox;
  DROP POLICY eventing_approver_event_insert ON eventing.domain_event;
  DROP POLICY eventing_approver_outbox_insert ON eventing.transactional_outbox;
  DROP POLICY eventing_authorizer_event_insert ON eventing.domain_event;
  DROP POLICY eventing_authorizer_outbox_insert ON eventing.transactional_outbox;
  DROP POLICY qms_learning_proposal_reviewer_select ON qms.learning_proposal;
  DROP POLICY qms_learning_proposal_approver_select ON qms.learning_proposal;
  DROP POLICY qms_learning_proposal_authorizer_select ON qms.learning_proposal;
  DROP POLICY qms_user_reviewer_select ON qms.user_projection;
  DROP POLICY qms_user_approver_select ON qms.user_projection;
  DROP POLICY qms_user_authorizer_select ON qms.user_projection;
  EXECUTE format('REVOKE INSERT ON eventing.domain_event,eventing.transactional_outbox FROM %I,%I,%I',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('REVOKE SELECT ON qms.organization,qms.user_projection,qms.learning_proposal,governance.model_policy,governance.agent_definition,normative.knowledge_layer_rule FROM %I,%I,%I',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('REVOKE EXECUTE ON FUNCTION audit.append_immutable_audit(uuid,text,uuid,text,text,text,text,uuid,uuid,timestamptz,text,text,text) FROM %I,%I,%I',reviewer_role,approver_role,authorizer_role);
  EXECUTE format('REVOKE USAGE ON SCHEMA qms,eventing,audit,governance,normative FROM %I,%I,%I',reviewer_role,approver_role,authorizer_role);
END $migration$;
DROP TABLE qms.learning_application_authorization;
DROP TABLE qms.learning_proposal_decision;
DROP TABLE qms.learning_proposal_review;
DROP FUNCTION qms.foundation_0019_validate_authorization();
DROP FUNCTION qms.foundation_0019_validate_decision();
DROP FUNCTION qms.foundation_0019_validate_review();
DROP FUNCTION qms.foundation_0019_current_target(text,uuid,uuid,text);
DROP FUNCTION qms.foundation_0019_reject_governance_mutation();
"""


def apply_phase23(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL, params=None)


def reverse_phase23(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL, params=None)


class Migration(migrations.Migration):
    dependencies = [("foundation", "0018_governed_learning_foundation")]
    operations = [
        migrations.RunPython(apply_phase23, reverse_phase23),
        migrations.CreateModel(
            name="LearningProposalReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("proposal_revision_snapshot", models.PositiveIntegerField()),
                ("proposal_predecessor_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("proposal_material_hash", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=80)), ("target_id", models.UUIDField()),
                ("target_lineage_id", models.UUIDField()), ("target_version", models.CharField(max_length=120)),
                ("target_hash", models.CharField(max_length=64)),
                ("target_status_snapshot", models.CharField(choices=[("valid", "Valid"), ("stale", "Stale")], max_length=16)),
                ("review_outcome", models.CharField(default="review_recorded", max_length=32)),
                ("findings", models.JSONField()), ("reviewed_governance_domains", models.JSONField(default=list)),
                ("reviewer_external_id_snapshot", models.UUIDField()),
                ("authority_context_version", models.CharField(max_length=120)),
                ("authority_decision_reference", models.CharField(max_length=255)),
                ("governance_scope", models.CharField(default="global", max_length=16)),
                ("policy_id", models.CharField(max_length=160)), ("trace_id", models.UUIDField()),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ], options={"db_table": 'qms"."learning_proposal_review', "managed": False},
        ),
        migrations.CreateModel(
            name="LearningProposalDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("proposal_revision_snapshot", models.PositiveIntegerField()),
                ("proposal_predecessor_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("proposal_material_hash", models.CharField(max_length=64)),
                ("review_ids_snapshot", models.JSONField(default=list)), ("review_set_hash", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=80)), ("target_id", models.UUIDField()),
                ("target_lineage_id", models.UUIDField()), ("target_version", models.CharField(max_length=120)),
                ("target_hash", models.CharField(max_length=64)),
                ("outcome", models.CharField(choices=[("approved_for_application", "Approved for application"), ("rejected", "Rejected"), ("changes_requested", "Changes requested")], max_length=32)),
                ("rationale", models.TextField()), ("decision_identity_hash", models.CharField(max_length=64, unique=True)),
                ("approver_external_id_snapshot", models.UUIDField()),
                ("authority_context_version", models.CharField(max_length=120)),
                ("authority_decision_reference", models.CharField(max_length=255)),
                ("governance_scope", models.CharField(default="global", max_length=16)),
                ("policy_id", models.CharField(max_length=160)), ("trace_id", models.UUIDField()),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ], options={"db_table": 'qms"."learning_proposal_decision', "managed": False},
        ),
        migrations.CreateModel(
            name="LearningApplicationAuthorization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("proposal_revision_snapshot", models.PositiveIntegerField()),
                ("proposal_material_hash", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=80)), ("target_id", models.UUIDField()),
                ("target_lineage_id", models.UUIDField()), ("target_version", models.CharField(max_length=120)),
                ("target_hash", models.CharField(max_length=64)), ("capability_id", models.CharField(max_length=160)),
                ("capability_version", models.CharField(default="v1", max_length=40)),
                ("authorization_status", models.CharField(choices=[("authorized", "Authorized")], default="authorized", max_length=24)),
                ("idempotency_key", models.CharField(max_length=255)), ("idempotency_hash", models.CharField(max_length=64)),
                ("authorizer_external_id_snapshot", models.UUIDField()),
                ("authority_context_version", models.CharField(max_length=120)),
                ("authority_decision_reference", models.CharField(max_length=255)),
                ("governance_scope", models.CharField(default="global", max_length=16)),
                ("policy_id", models.CharField(max_length=160)), ("trace_id", models.UUIDField()),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ], options={"db_table": 'qms"."learning_application_authorization', "managed": False},
        ),
    ]
