# Generated by Django 4.2.7 on 2025-12-20 01:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: EST-01, OPE-02, APO-03', max_length=20, verbose_name='Código del Proceso')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proceso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('process_type', models.CharField(choices=[('strategic', 'Estratégico'), ('operational', 'Operativo'), ('support', 'Apoyo')], max_length=20, verbose_name='Tipo de Proceso')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo del Proceso')),
                ('owner', models.CharField(help_text='Persona o cargo responsable', max_length=100, verbose_name='Dueño del Proceso')),
                ('inputs', models.JSONField(default=list, help_text='Recursos, información, documentos que requiere el proceso', verbose_name='Entradas')),
                ('outputs', models.JSONField(default=list, help_text='Productos, servicios, documentos que genera el proceso', verbose_name='Salidas')),
                ('resources', models.JSONField(default=list, help_text='Personal, equipos, infraestructura necesaria', verbose_name='Recursos')),
                ('kpis', models.JSONField(default=list, verbose_name='Indicadores de Desempeño (KPIs)')),
                ('risks', models.JSONField(default=list, verbose_name='Riesgos Identificados')),
                ('controls', models.JSONField(default=list, help_text='Controles para gestionar los riesgos', verbose_name='Controles')),
                ('criticality_score', models.FloatField(default=0.5, help_text='0 = No crítico, 1 = Altamente crítico', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Nivel de Criticidad')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Proceso Crítico')),
                ('documented_in', models.CharField(blank=True, help_text='Referencia al documento del procedimiento', max_length=200, verbose_name='Documentado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['process_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mapa de Procesos Organizacional', max_length=255, verbose_name='Título del Mapa')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Vigencia')),
                ('total_processes', models.IntegerField(default=0, verbose_name='Total de Procesos')),
                ('strategic_count', models.IntegerField(default=0, verbose_name='Procesos Estratégicos')),
                ('operational_count', models.IntegerField(default=0, verbose_name='Procesos Operativos')),
                ('support_count', models.IntegerField(default=0, verbose_name='Procesos de Apoyo')),
                ('interaction_analysis', models.JSONField(default=dict, help_text='Matriz de interacciones entre procesos', verbose_name='Análisis de Interacciones')),
                ('critical_processes', models.JSONField(default=list, help_text='Lista de procesos identificados como críticos', verbose_name='Procesos Críticos')),
                ('recommendations', models.JSONField(default=list, verbose_name='Recomendaciones')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('active', 'Activo')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Sistema IA', max_length=100)),
                ('scope_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_maps', to='asb.scopedefinition', verbose_name='Definición de Alcance')),
            ],
            options={
                'verbose_name': 'Mapa de Procesos',
                'verbose_name_plural': 'Mapas de Procesos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('input_output', 'Entrada-Salida'), ('information', 'Flujo de Información'), ('dependency', 'Dependencia'), ('resource_sharing', 'Recursos Compartidos')], max_length=20, verbose_name='Tipo de Interacción')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la Interacción')),
                ('exchanged_items', models.JSONField(default=list, help_text='Documentos, información, productos intercambiados', verbose_name='Items Intercambiados')),
                ('frequency', models.CharField(choices=[('continuous', 'Continuo'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('on_demand', 'Bajo Demanda')], default='on_demand', max_length=20, verbose_name='Frecuencia')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Interacción Crítica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='spm.processmap', verbose_name='Mapa de Procesos')),
                ('source_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_interactions', to='spm.process', verbose_name='Proceso Origen')),
                ('target_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_interactions', to='spm.process', verbose_name='Proceso Destino')),
            ],
            options={
                'verbose_name': 'Interacción entre Procesos',
                'verbose_name_plural': 'Interacciones entre Procesos',
                'ordering': ['source_process', 'target_process'],
            },
        ),
        migrations.CreateModel(
            name='ProcessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Secuencia')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Actividad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('responsible', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('estimated_duration', models.CharField(blank=True, help_text='Ej: 2 horas, 1 día', max_length=50, verbose_name='Duración Estimada')),
                ('tools_required', models.JSONField(default=list, verbose_name='Herramientas Requeridas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='spm.process', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Actividad del Proceso',
                'verbose_name_plural': 'Actividades del Proceso',
                'ordering': ['process', 'sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='process_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='spm.processmap', verbose_name='Mapa de Procesos'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('process_map', 'code')},
        ),
    ]
