# Generated by Django 4.2.7 on 2026-03-09 01:54

from django.db import migrations, models


def backfill_processmap_org_id(apps, schema_editor):
    ProcessMap = apps.get_model('spm', 'ProcessMap')

    maps = (
        ProcessMap.objects
        .filter(organization_id__isnull=True)
        .exclude(scope_definition_id__isnull=True)
        .select_related('scope_definition')
    )

    for process_map in maps.iterator():
        scope = getattr(process_map, 'scope_definition', None)
        org_id = getattr(scope, 'organization_id', None)
        if org_id:
            process_map.organization_id = org_id
            process_map.save(update_fields=['organization_id'])


def reverse_backfill_processmap_org_id(apps, schema_editor):
    ProcessMap = apps.get_model('spm', 'ProcessMap')
    ProcessMap.objects.update(organization_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0002_scopedefinition_organization_id'),
        ('spm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmap',
            name='organization_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID de Organización'),
        ),
        migrations.RunPython(backfill_processmap_org_id, reverse_backfill_processmap_org_id),
    ]
