# Generated by Django 4.2.7 on 2026-04-06 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0002_processmap_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='carbon_intensity_category',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('unknown', 'Desconocida')], default='unknown', max_length=20, verbose_name='Intensidad de Carbono'),
        ),
        migrations.AddField(
            model_name='process',
            name='climate_exposure_level',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Exposición Climática'),
        ),
        migrations.AddField(
            model_name='process',
            name='resilience_score',
            field=models.FloatField(default=50.0, help_text='Capacidad de respuesta del proceso ante disrupciones (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score de Resiliencia'),
        ),
        migrations.AddField(
            model_name='process',
            name='supply_chain_risk',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('unknown', 'Desconocido')], default='unknown', max_length=20, verbose_name='Riesgo de Cadena de Suministro'),
        ),
    ]
