# Generated by Django 4.2.7 on 2026-02-13 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=200)),
                ('nc_number', models.CharField(max_length=50, verbose_name='Numero de NC')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('internal_audit', 'Auditoria interna'), ('customer_complaint', 'Queja de cliente'), ('process_monitoring', 'Monitoreo de procesos'), ('product_inspection', 'Inspeccion de producto'), ('management_review', 'Revision por la direccion'), ('supplier_issue', 'Problema de proveedor'), ('other', 'Otro')], max_length=50)),
                ('detection_date', models.DateField()),
                ('severity', models.CharField(choices=[('critical', 'Critica'), ('major', 'Mayor'), ('minor', 'Menor')], max_length=20)),
                ('affected_process', models.CharField(blank=True, max_length=200)),
                ('iso_clause_reference', models.CharField(blank=True, max_length=100)),
                ('impact_description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('immediate_action_taken', models.TextField(blank=True)),
                ('containment_measures', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('analysis', 'En analisis'), ('action_plan', 'Plan de accion definido'), ('implementing', 'Implementando acciones'), ('verification', 'Verificacion'), ('closed', 'Cerrada'), ('rejected', 'Rechazada')], default='open', max_length=20)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('target_closure_date', models.DateField(blank=True, null=True)),
                ('actual_closure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_nonconformities_detected', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_nonconformities_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'No Conformidad (Mejora)',
                'verbose_name_plural': 'No Conformidades (Mejora)',
                'ordering': ['-detection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('action_number', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('corrective', 'Correctiva'), ('preventive', 'Preventiva'), ('improvement', 'Mejora')], max_length=20)),
                ('root_cause_analysis', models.TextField(help_text='5 Whys, Ishikawa, etc.')),
                ('root_cause_identified', models.TextField()),
                ('analysis_method', models.CharField(blank=True, max_length=100)),
                ('action_description', models.TextField()),
                ('implementation_steps', models.TextField()),
                ('resources_required', models.TextField(blank=True)),
                ('planned_start_date', models.DateField()),
                ('planned_completion_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('verification_method', models.TextField(blank=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_result', models.TextField(blank=True)),
                ('effectiveness_criteria', models.TextField(blank=True)),
                ('effectiveness_review_date', models.DateField(blank=True, null=True)),
                ('effectiveness_result', models.TextField(blank=True)),
                ('is_effective', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En progreso'), ('implemented', 'Implementada'), ('verified', 'Verificada'), ('effective', 'Efectiva'), ('not_effective', 'No efectiva'), ('cancelled', 'Cancelada')], default='planned', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='improvement.nonconformity')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions_responsible', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accion Correctiva',
                'verbose_name_plural': 'Acciones Correctivas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContinualImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=200)),
                ('initiative_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('improvement_type', models.CharField(choices=[('process', 'Mejora de proceso'), ('product', 'Mejora de producto'), ('service', 'Mejora de servicio'), ('system', 'Mejora del SGC'), ('technology', 'Mejora tecnologica'), ('methodology', 'Mejora metodologica')], max_length=50)),
                ('current_situation', models.TextField()),
                ('proposed_improvement', models.TextField()),
                ('expected_benefits', models.TextField()),
                ('alignment_with_objectives', models.TextField(blank=True)),
                ('estimated_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_roi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payback_period_months', models.IntegerField(blank=True, null=True)),
                ('success_criteria', models.TextField()),
                ('kpis_to_measure', models.JSONField(blank=True, default=list)),
                ('baseline_measurements', models.TextField(blank=True)),
                ('target_measurements', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('proposed_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('implementation_plan', models.TextField(blank=True)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('risks_and_mitigation', models.TextField(blank=True)),
                ('actual_results', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Propuesta'), ('under_evaluation', 'En evaluacion'), ('approved', 'Aprobada'), ('in_progress', 'En progreso'), ('implemented', 'Implementada'), ('measuring_results', 'Midiendo resultados'), ('successful', 'Exitosa'), ('unsuccessful', 'No exitosa'), ('cancelled', 'Cancelada')], default='proposed', max_length=30)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_initiatives_champion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mejora Continua',
                'verbose_name_plural': 'Mejoras Continuas',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='nonconformity',
            index=models.Index(fields=['organization_id', 'status'], name='improvement_organiz_7cd41c_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformity',
            index=models.Index(fields=['organization_id', 'severity'], name='improvement_organiz_6b49d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nonconformity',
            unique_together={('organization_id', 'nc_number')},
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['organization_id', 'status'], name='improvement_organiz_a3720d_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['organization_id', 'action_type'], name='improvement_organiz_f595b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='correctiveaction',
            unique_together={('organization_id', 'action_number')},
        ),
        migrations.AddIndex(
            model_name='continualimprovement',
            index=models.Index(fields=['organization_id', 'status'], name='improvement_organiz_e88d59_idx'),
        ),
        migrations.AddIndex(
            model_name='continualimprovement',
            index=models.Index(fields=['organization_id', 'priority'], name='improvement_organiz_c83c33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='continualimprovement',
            unique_together={('organization_id', 'initiative_number')},
        ),
    ]
