# Generated by Django 4.2.7 on 2025-11-29 22:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(help_text='Ej: expectation_change, contact_change, etc.', max_length=100, verbose_name='Tipo de Cambio')),
                ('previous_state', models.JSONField(help_text='Snapshot del estado previo', verbose_name='Estado Anterior')),
                ('new_state', models.JSONField(help_text='Snapshot del nuevo estado', verbose_name='Nuevo Estado')),
                ('similarity_score', models.FloatField(default=1.0, help_text='Qué tan similares son los estados (0=completamente diferente, 1=idéntico)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de Similitud')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Log de Cambios',
                'verbose_name_plural': 'Logs de Cambios',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderEngagementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=200)),
                ('objectives', models.JSONField(default=list, help_text='Lista de objetivos específicos', verbose_name='Objetivos del Plan')),
                ('actions', models.JSONField(default=list, help_text='Lista de acciones con responsables y fechas', verbose_name='Acciones Planificadas')),
                ('success_metrics', models.JSONField(default=list, help_text='KPIs para medir efectividad', verbose_name='Métricas de Éxito')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effectiveness_score', models.FloatField(blank=True, help_text='Evaluación post-ejecución de 0 a 10', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Score de Efectividad')),
            ],
            options={
                'verbose_name': 'Plan de Engagement',
                'verbose_name_plural': 'Planes de Engagement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('stakeholder_type', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('empleado', 'Empleado'), ('accionista', 'Accionista'), ('regulador', 'Entidad Reguladora'), ('comunidad', 'Comunidad Local'), ('socio', 'Socio Estratégico'), ('competidor', 'Competidor'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Stakeholder')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organización')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10, verbose_name='Nivel de Poder')),
                ('interest', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10, verbose_name='Nivel de Interés')),
                ('influence_score', models.FloatField(default=0.0, help_text='Score compuesto de 0.0 a 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de Influencia (calculado por IA)')),
                ('satisfaction_score', models.FloatField(default=5.0, help_text='De 0 a 10', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Score de Satisfacción')),
                ('expectations', models.JSONField(default=list, help_text='Lista de expectativas del stakeholder', verbose_name='Expectativas')),
                ('requirements', models.JSONField(default=list, help_text='Requisitos específicos del stakeholder', verbose_name='Requisitos')),
                ('communication_frequency', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20, verbose_name='Frecuencia de Comunicación')),
                ('preferred_channel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Canal de Comunicación Preferido')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True, verbose_name='Último Contacto')),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'ordering': ['-influence_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('colaboracion', 'Colaboración'), ('cliente-proveedor', 'Cliente-Proveedor'), ('competencia', 'Competencia'), ('regulatoria', 'Regulatoria'), ('contractual', 'Contractual'), ('general', 'General')], default='general', max_length=20)),
                ('strength', models.FloatField(default=0.5, help_text='0.0 = débil, 1.0 = muy fuerte', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Fuerza de la Relación')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='sie.stakeholderprofile')),
                ('to_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='sie.stakeholderprofile')),
            ],
            options={
                'verbose_name': 'Relación entre Stakeholders',
                'verbose_name_plural': 'Relaciones entre Stakeholders',
            },
        ),
        migrations.AddIndex(
            model_name='stakeholderprofile',
            index=models.Index(fields=['stakeholder_type', 'is_active'], name='sie_stakeho_stakeho_b75986_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderprofile',
            index=models.Index(fields=['-influence_score'], name='sie_stakeho_influen_ba0718_idx'),
        ),
        migrations.AddField(
            model_name='stakeholderengagementplan',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_plans', to='sie.stakeholderprofile'),
        ),
        migrations.AddField(
            model_name='stakeholderchangelog',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sie.stakeholderprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='stakeholderrelationship',
            unique_together={('from_stakeholder', 'to_stakeholder')},
        ),
        migrations.AddIndex(
            model_name='stakeholderchangelog',
            index=models.Index(fields=['stakeholder', '-detected_at'], name='sie_stakeho_stakeho_17a57f_idx'),
        ),
    ]
