# Generated by Django 4.2.7 on 2025-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderprofile',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Marcado automáticamente por IA si influencia > 0.7', verbose_name='Stakeholder Crítico'),
        ),
    ]
