# Generated by Django 4.2.7 on 2026-03-11 16:18

from django.db import migrations, models


def backfill_organization_id(apps, schema_editor):
    """Populate organization_id by matching the text 'organization' field with Organization.name."""
    StakeholderProfile = apps.get_model('sie', 'StakeholderProfile')
    Organization = apps.get_model('core', 'Organization')

    org_name_to_id = {org.name: org.id for org in Organization.objects.all()}

    to_update = []
    for sp in StakeholderProfile.objects.filter(
        organization_id__isnull=True
    ).exclude(organization='').exclude(organization__isnull=True):
        org_id = org_name_to_id.get(sp.organization)
        if org_id:
            sp.organization_id = org_id
            to_update.append(sp)

    StakeholderProfile.objects.bulk_update(to_update, ['organization_id'])


def reverse_backfill(apps, schema_editor):
    StakeholderProfile = apps.get_model('sie', 'StakeholderProfile')
    StakeholderProfile.objects.update(organization_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sie', '0002_stakeholderprofile_is_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderprofile',
            name='organization_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID de Organización'),
        ),
        migrations.RunPython(backfill_organization_id, reverse_code=reverse_backfill),
    ]
