# Generated by Django 4.2.7 on 2026-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sie', '0003_stakeholderprofile_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderprofile',
            name='stakeholder_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('empleado', 'Empleado'), ('accionista', 'Accionista'), ('regulador', 'Entidad Reguladora'), ('regulatory_environmental', 'Regulador Ambiental'), ('comunidad', 'Comunidad Local'), ('community_climate_affected', 'Comunidad Afectada por Clima'), ('esg_investor', 'Inversor ESG'), ('socio', 'Socio Estratégico'), ('competidor', 'Competidor'), ('otro', 'Otro')], max_length=40, verbose_name='Tipo de Stakeholder'),
        ),
    ]
