# Generated by Django 4.2.7 on 2025-12-18 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Alcance del Sistema de Gestión de Calidad', max_length=255, verbose_name='Título del Alcance')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Vigencia')),
                ('organizational_boundaries', models.JSONField(default=dict, help_text='Estructura, ubicaciones, departamentos incluidos', verbose_name='Límites Organizacionales')),
                ('products_services', models.JSONField(default=list, help_text='Lista de productos/servicios incluidos en el alcance', verbose_name='Productos y Servicios')),
                ('applicable_requirements', models.JSONField(default=dict, help_text='Requisitos ISO 9001 aplicables y justificaciones', verbose_name='Requisitos Aplicables')),
                ('exclusions', models.JSONField(default=list, help_text='Requisitos excluidos con justificación', verbose_name='Exclusiones')),
                ('scope_statement', models.TextField(blank=True, help_text='Texto generado automáticamente del alcance', verbose_name='Declaración de Alcance')),
                ('coverage_analysis', models.JSONField(default=dict, help_text='Análisis de qué tan completo es el alcance', verbose_name='Análisis de Cobertura')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('active', 'Activo'), ('superseded', 'Reemplazado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Sistema IA', max_length=100)),
                ('context_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_definitions', to='core.contextanalysis', verbose_name='Análisis de Contexto Relacionado')),
            ],
            options={
                'verbose_name': 'Definición de Alcance',
                'verbose_name_plural': 'Definiciones de Alcance',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200, verbose_name='Nombre del Proceso')),
                ('process_code', models.CharField(blank=True, max_length=50, verbose_name='Código del Proceso')),
                ('process_type', models.CharField(choices=[('strategic', 'Estratégico'), ('operational', 'Operativo'), ('support', 'Apoyo')], max_length=20, verbose_name='Tipo de Proceso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('inputs', models.JSONField(default=list, verbose_name='Entradas del Proceso')),
                ('outputs', models.JSONField(default=list, verbose_name='Salidas del Proceso')),
                ('kpis', models.JSONField(default=list, verbose_name='Indicadores (KPIs)')),
                ('is_included', models.BooleanField(default=True, verbose_name='Incluido en Alcance')),
                ('exclusion_reason', models.TextField(blank=True, verbose_name='Razón de Exclusión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='asb.scopedefinition', verbose_name='Definición de Alcance')),
            ],
            options={
                'verbose_name': 'Proceso en Alcance',
                'verbose_name_plural': 'Procesos en Alcance',
                'ordering': ['process_type', 'process_name'],
            },
        ),
        migrations.CreateModel(
            name='LocationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, verbose_name='Nombre de la Ubicación')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('location_type', models.CharField(choices=[('headquarters', 'Sede Principal'), ('branch', 'Sucursal'), ('warehouse', 'Almacén/Bodega'), ('plant', 'Planta de Producción'), ('office', 'Oficina'), ('remote', 'Trabajo Remoto')], max_length=20, verbose_name='Tipo de Ubicación')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('activities', models.JSONField(default=list, verbose_name='Actividades Realizadas')),
                ('employee_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Empleados')),
                ('is_included', models.BooleanField(default=True, verbose_name='Incluida en Alcance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='asb.scopedefinition', verbose_name='Definición de Alcance')),
            ],
            options={
                'verbose_name': 'Ubicación en Alcance',
                'verbose_name_plural': 'Ubicaciones en Alcance',
                'ordering': ['country', 'city', 'location_name'],
            },
        ),
    ]
