# Generated by Django 4.2.7 on 2026-03-09 01:54

from django.db import migrations, models


def backfill_scope_org_id(apps, schema_editor):
    ScopeDefinition = apps.get_model('asb', 'ScopeDefinition')

    scopes = (
        ScopeDefinition.objects
        .filter(organization_id__isnull=True)
        .exclude(context_analysis_id__isnull=True)
        .select_related('context_analysis')
    )

    for scope in scopes.iterator():
        context = getattr(scope, 'context_analysis', None)
        org_id = getattr(context, 'organization_id', None)
        if org_id:
            scope.organization_id = org_id
            scope.save(update_fields=['organization_id'])


def reverse_backfill_scope_org_id(apps, schema_editor):
    ScopeDefinition = apps.get_model('asb', 'ScopeDefinition')
    ScopeDefinition.objects.update(organization_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedefinition',
            name='organization_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID de Organización'),
        ),
        migrations.RunPython(backfill_scope_org_id, reverse_backfill_scope_org_id),
    ]
