# Generated by Django 4.2.7 on 2026-04-06 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0002_scopedefinition_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedefinition',
            name='climate_readiness_score',
            field=models.FloatField(default=0.0, help_text='Puntaje de preparación climática del alcance (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score de Madurez Climática'),
        ),
        migrations.AddField(
            model_name='scopedefinition',
            name='digital_readiness_score',
            field=models.FloatField(default=0.0, help_text='Puntaje de preparación digital del alcance (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score de Madurez Digital'),
        ),
        migrations.AddField(
            model_name='scopedefinition',
            name='environmental_criteria',
            field=models.JSONField(default=dict, help_text='Criterios de materialidad ambiental y climática para el alcance', verbose_name='Criterios Ambientales'),
        ),
    ]
