# Generated by Django 4.2.7 on 2026-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
