# Generated by Django 4.2.7 on 2026-01-22 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_document_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='NIT/RUC/RFC')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('basic', 'Básico'), ('professional', 'Profesional'), ('enterprise', 'Empresarial')], default='basic', max_length=50)),
                ('max_users', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('org_admin', 'Administrador'), ('iso_manager', 'Gestor ISO'), ('auditor', 'Auditor'), ('user', 'Usuario'), ('viewer', 'Solo Lectura')], default='user', max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='light', max_length=10)),
                ('language', models.CharField(default='es', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_sca_enabled', models.BooleanField(default=True, verbose_name='Context Analyzer')),
                ('ai_sie_enabled', models.BooleanField(default=True, verbose_name='Stakeholder Intelligence')),
                ('ai_asb_enabled', models.BooleanField(default=True, verbose_name='Scope Builder')),
                ('ai_spm_enabled', models.BooleanField(default=True, verbose_name='Process Mapper')),
                ('ai_auto_analysis', models.BooleanField(default=False, verbose_name='Análisis automático')),
                ('ai_analysis_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('manual', 'Manual')], default='weekly', max_length=20)),
                ('notify_risk_critical', models.BooleanField(default=True)),
                ('notify_risk_high', models.BooleanField(default=True)),
                ('notify_objective_deadline', models.BooleanField(default=True)),
                ('notify_document_upload', models.BooleanField(default=False)),
                ('notify_stakeholder_change', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('iso_standard', models.CharField(default='ISO 9001:2015', max_length=50)),
                ('fiscal_year_start', models.IntegerField(choices=[(1, 'Mes 1'), (2, 'Mes 2'), (3, 'Mes 3'), (4, 'Mes 4'), (5, 'Mes 5'), (6, 'Mes 6'), (7, 'Mes 7'), (8, 'Mes 8'), (9, 'Mes 9'), (10, 'Mes 10'), (11, 'Mes 11'), (12, 'Mes 12')], default=1)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=20)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.organization')),
            ],
            options={
                'db_table': 'organization_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('export', 'Exportación'), ('backup', 'Respaldo')], max_length=20)),
                ('module', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ISOClauseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(max_length=10)),
                ('clause_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_applicable', models.BooleanField(default=True)),
                ('exclusion_justification', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_clauses', to='core.organization')),
            ],
            options={
                'db_table': 'iso_clause_configs',
                'ordering': ['clause_number'],
                'unique_together': {('organization', 'clause_number')},
            },
        ),
    ]
