# Generated by Django 4.2.7 on 2026-02-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_id',
            field=models.CharField(blank=True, help_text='UUID desde Admin Apps', max_length=36, null=True, unique=True),
        ),
    ]
