# Generated by Django 4.2.7 on 2026-02-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_onboarding_and_multi_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isoclauseconfig',
            options={'ordering': ['standard_code', 'clause_number']},
        ),
    ]
