# Generated by Django 4.2.7 on 2026-02-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_preferred_language_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='preferred_language',
            field=models.CharField(choices=[('es-LATAM', 'Español (LATAM)'), ('en', 'English'), ('pt', 'Português')], default='es-LATAM', max_length=20),
        ),
    ]
