# Generated by Django 4.2.7 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizationsettings_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='onboarding_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='preferred_response_tone',
            field=models.CharField(choices=[('manager', 'Lenguaje gerente'), ('technical', 'Lenguaje técnico')], default='manager', max_length=20),
        ),
    ]
