# Generated by Django 4.2.7 on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organizationsettings_onboarding_profile_and_tone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('input_profile', models.JSONField(blank=True, default=dict)),
                ('organizational_profile_output', models.JSONField(blank=True, default=dict)),
                ('impact_savings_output', models.JSONField(blank=True, default=dict)),
                ('purpose_alignment_output', models.JSONField(blank=True, default=dict)),
                ('summary_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_snapshots', to='core.organization')),
            ],
            options={
                'db_table': 'onboarding_insight_snapshots',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'version')},
            },
        ),
    ]
