# Generated by Django 4.2.7 on 2026-03-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_billingpayment_evidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextanalysis',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_analyses', to='core.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.organization'),
        ),
        migrations.AddField(
            model_name='processmap',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_maps', to='core.organization'),
        ),
        migrations.AddField(
            model_name='qualityobjective',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_objectives', to='core.organization'),
        ),
        migrations.AddField(
            model_name='riskmatrix',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_matrices', to='core.organization'),
        ),
        migrations.AddField(
            model_name='stakeholderprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='core.organization'),
        ),
    ]
