# Generated by Django 4.2.7 on 2026-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notificationdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextanalysis',
            name='climate_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contextanalysis',
            name='environmental_scope',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
