# Generated by Django 4.2.7 on 2026-04-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contextanalysis_climate_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_organiz_a85fc0_idx',
            old_name='notificatio_organiz_6e1f3f_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_status_92d529_idx',
            old_name='notificatio_status_8f275b_idx',
        ),
    ]
