# Generated by Django 4.2.7 on 2026-04-06 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_rename_notificatio_organiz_6e1f3f_idx_notificatio_organiz_a85fc0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContextSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ipcc', 'IPCC'), ('un', 'ONU'), ('iso', 'ISO'), ('regulator', 'Regulador'), ('industry', 'Industria')], max_length=20)),
                ('source_name', models.CharField(max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('signal_hash', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('impact_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], default='medium', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_context_signals', to='core.organization')),
            ],
            options={
                'db_table': 'external_context_signals',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('regulatory_change', 'Cambio regulatorio'), ('climate_event', 'Evento climatico'), ('supply_chain_risk', 'Riesgo de cadena de suministro'), ('process_exposure', 'Exposicion de proceso'), ('stakeholder_pressure', 'Presion de stakeholder')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], default='medium', max_length=20)),
                ('source_module', models.CharField(default='SCA', max_length=20)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('ai_audit_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En progreso'), ('acknowledged', 'Reconocida'), ('closed', 'Cerrada')], default='open', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('external_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.externalcontextsignal')),
                ('linked_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_alerts', to='core.riskmatrix')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_alerts', to='core.organization')),
            ],
            options={
                'db_table': 'environmental_risk_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalcontextsignal',
            index=models.Index(fields=['organization', 'source_type'], name='external_co_organiz_696d46_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontextsignal',
            index=models.Index(fields=['impact_level', '-fetched_at'], name='external_co_impact__e60801_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcontextsignal',
            unique_together={('organization', 'source_name', 'signal_hash')},
        ),
        migrations.AddIndex(
            model_name='environmentalriskalert',
            index=models.Index(fields=['organization', 'severity'], name='environment_organiz_327b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalriskalert',
            index=models.Index(fields=['status', '-created_at'], name='environment_status_96c07f_idx'),
        ),
    ]
