# Generated by Django 4.2.7 on 2026-02-09 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Rol')),
                ('code', models.CharField(max_length=50, verbose_name='Código del Rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nivel Jerárquico')),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('authorities', models.JSONField(blank=True, default=list)),
                ('required_competencies', models.JSONField(blank=True, default=list)),
                ('is_qms_role', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='leadership.organizationalrole')),
            ],
            options={
                'verbose_name': 'Rol Organizacional',
                'verbose_name_plural': 'Roles Organizacionales',
                'ordering': ['level', 'name'],
                'unique_together': {('organization_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporal'), ('acting', 'Interino')], default='permanent', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leadership.organizationalrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RACIMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raci_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matriz RACI',
                'verbose_name_plural': 'Matrices RACI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RACIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('accountable_roles', models.ManyToManyField(blank=True, related_name='raci_accountable', to='leadership.organizationalrole')),
                ('consulted_roles', models.ManyToManyField(blank=True, related_name='raci_consulted', to='leadership.organizationalrole')),
                ('informed_roles', models.ManyToManyField(blank=True, related_name='raci_informed', to='leadership.organizationalrole')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leadership.racimatrix')),
                ('responsible_roles', models.ManyToManyField(blank=True, related_name='raci_responsible', to='leadership.organizationalrole')),
            ],
            options={
                'verbose_name': 'Entrada RACI',
                'verbose_name_plural': 'Entradas RACI',
                'ordering': ['matrix', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=200)),
                ('commitment_type', models.CharField(choices=[('responsibility', 'Responsabilidad por SGC'), ('policy', 'Política y Objetivos'), ('integration', 'Integración en Procesos'), ('resources', 'Disponibilidad de Recursos'), ('importance', 'Comunicación de Importancia'), ('results', 'Logro de Resultados'), ('engagement', 'Participación de Personal'), ('improvement', 'Promoción de Mejora'), ('management', 'Apoyo a Gestión')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('meeting', 'Acta de Reunión'), ('communication', 'Comunicación'), ('decision', 'Decisión Documentada'), ('resource_allocation', 'Asignación de Recursos'), ('review', 'Revisión por la Dirección'), ('policy_update', 'Actualización de Política'), ('other', 'Otro')], max_length=50)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='leadership/commitments/')),
                ('evidence_url', models.URLField(blank=True)),
                ('commitment_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('verified', 'Verificado')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compromiso de Liderazgo',
                'verbose_name_plural': 'Compromisos de Liderazgo',
                'ordering': ['-commitment_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFocusEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=200)),
                ('focus_type', models.CharField(choices=[('requirements', 'Determinación de Requisitos'), ('risks', 'Determinación de Riesgos'), ('satisfaction', 'Enfoque en Satisfacción'), ('compliance', 'Cumplimiento Legal/Reglamentario')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('results', models.TextField(blank=True)),
                ('action_date', models.DateField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='leadership/customer_focus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de Enfoque al Cliente',
                'verbose_name_plural': 'Evidencias de Enfoque al Cliente',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='QualityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(help_text='ID de la organización (integración con Admin Apps)')),
                ('organization_name', models.CharField(help_text='Nombre de la organización (cache)', max_length=200)),
                ('version', models.CharField(help_text='Versión de la política (ej: 1.0, 2.1)', max_length=20)),
                ('title', models.CharField(default='Política de Calidad', max_length=200)),
                ('content', models.TextField(help_text='Texto completo de la política de calidad', verbose_name='Contenido de la Política')),
                ('customer_focus', models.TextField(blank=True, help_text='Cómo la política demuestra enfoque al cliente', verbose_name='Enfoque al Cliente')),
                ('framework_for_objectives', models.TextField(blank=True, help_text='Cómo proporciona marco para objetivos de calidad', verbose_name='Marco para Objetivos')),
                ('commitment_requirements', models.TextField(blank=True, help_text='Compromiso de cumplir requisitos aplicables', verbose_name='Compromiso con Requisitos')),
                ('commitment_improvement', models.TextField(blank=True, help_text='Compromiso de mejora continua del SGC', verbose_name='Compromiso con Mejora Continua')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobada'), ('active', 'Activa'), ('obsolete', 'Obsoleta')], default='draft', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, help_text='Fecha desde la cual la política está vigente', null=True, verbose_name='Fecha de Vigencia')),
                ('review_date', models.DateField(blank=True, help_text='Fecha programada para próxima revisión', null=True, verbose_name='Fecha de Próxima Revisión')),
                ('is_published', models.BooleanField(default=False, help_text='Si está publicada y disponible para toda la organización')),
                ('communication_channels', models.JSONField(blank=True, default=list, help_text='Canales donde se ha comunicado')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Versión PDF firmada de la política', null=True, upload_to='leadership/policies/pdfs/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política de Calidad',
                'verbose_name_plural': 'Políticas de Calidad',
                'ordering': ['-version', '-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'status'], name='leadership__organiz_fe46cd_idx'), models.Index(fields=['organization_id', 'is_published'], name='leadership__organiz_a3fcf8_idx')],
                'unique_together': {('organization_id', 'version')},
            },
        ),
    ]
