# Generated by Django 4.2.7 on 2026-04-11 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('review_type', models.CharField(choices=[('scheduled', 'Programada'), ('extraordinary', 'Extraordinaria'), ('follow_up', 'Seguimiento')], default='scheduled', max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='planned', max_length=20)),
                ('attendee_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de usuarios asistentes')),
                ('agenda_items', models.JSONField(blank=True, default=list, help_text='Puntos de la agenda: [{title, owner, notes}]')),
                ('ai_brief', models.TextField(blank=True, help_text='Brief pre-reunión generado por IA (borrador, requiere aprobación)')),
                ('ai_brief_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_brief_approved_at', models.DateTimeField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True)),
                ('minutes_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_brief_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_briefs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_reviews', to=settings.AUTH_USER_MODEL)),
                ('minutes_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_review_minutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión por la Dirección',
                'verbose_name_plural': 'Revisiones por la Dirección',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='QualityCultureSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('closed', 'Cerrada'), ('archived', 'Archivada')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('questions', models.JSONField(default=list, help_text="[{id, text, type: 'scale'|'choice'|'text', options}]")),
                ('min_responses_for_analysis', models.IntegerField(default=5, help_text='Mínimo de respuestas para mostrar resultados (protección privacidad)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta de Cultura',
                'verbose_name_plural': 'Encuestas de Cultura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('decision_type', models.CharField(choices=[('policy_change', 'Cambio de Política'), ('objective_change', 'Cambio de Objetivo'), ('resource_allocation', 'Asignación de Recursos'), ('process_change', 'Cambio de Proceso'), ('corrective_action', 'Acción Correctiva'), ('improvement_opportunity', 'Oportunidad de Mejora'), ('strategic_decision', 'Decisión Estratégica')], max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Propuesta'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('rejected', 'Rechazada')], default='proposed', max_length=20)),
                ('ai_suggested', models.BooleanField(default=False, help_text='Sugerida por IA — requiere aprobación humana explícita')),
                ('rationale', models.TextField(blank=True, help_text="Por qué se tomó esta decisión (registro del 'por qué')")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(help_text='Regla ISO: toda decisión debe tener responsable asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_decisions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='leadership.managementreview')),
            ],
            options={
                'verbose_name': 'Decisión de Revisión',
                'verbose_name_plural': 'Decisiones de Revisión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True, help_text='ID de la organización')),
                ('node_type', models.CharField(choices=[('directive_decision', 'Decisión Directiva'), ('quality_policy', 'Política de Calidad'), ('objective', 'Objetivo de Calidad'), ('process', 'Proceso'), ('kpi', 'KPI / Indicador'), ('risk', 'Riesgo'), ('action', 'Acción'), ('result', 'Resultado')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='PK del objeto referenciado en el sistema (ej. QualityPolicy.id)', null=True)),
                ('reference_model', models.CharField(blank=True, help_text="Modelo Django referenciado (ej. 'leadership.QualityPolicy')", max_length=100)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('expected_impact', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_evidence_nodes', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_evidence_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nodo de Evidencia',
                'verbose_name_plural': 'Nodos de Evidencia',
                'ordering': ['node_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('derives_from', 'Deriva de'), ('supports', 'Soporta'), ('measures', 'Mide'), ('mitigates', 'Mitiga'), ('generates', 'Genera'), ('implements', 'Implementa')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_edges', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='leadership.evidencenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='leadership.evidencenode')),
            ],
            options={
                'verbose_name': 'Arista de Evidencia',
                'verbose_name_plural': 'Aristas de Evidencia',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('workflow_type', models.CharField(choices=[('quality_policy', 'Política de Calidad'), ('review_minutes', 'Acta de Revisión'), ('review_decision', 'Decisión de Revisión'), ('raci_matrix', 'Matriz RACI'), ('strategic_decision', 'Decisión Estratégica'), ('resource_allocation', 'Asignación de Recursos'), ('objective', 'Objetivo de Calidad'), ('evidence_node', 'Nodo de Evidencia')], max_length=30)),
                ('reference_id', models.IntegerField()),
                ('reference_model', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('digital_signature', models.CharField(help_text='SHA-256 del snapshot de contenido + ID usuario + timestamp', max_length=64)),
                ('content_snapshot', models.JSONField(help_text='Snapshot inmutable del contenido aprobado en el momento de firma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Aprobación',
                'verbose_name_plural': 'Registros de Aprobación',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGovernanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True)),
                ('module', models.CharField(default='leadership', help_text='Módulo que originó la operación', max_length=50)),
                ('operation', models.CharField(help_text="Operación: 'policy_draft', 'voc_analysis', 'raci_gaps', etc.", max_length=100)),
                ('model_version', models.CharField(default='unknown', max_length=100)),
                ('prompt_template', models.CharField(help_text='Nombre de la plantilla de prompt (no el prompt completo)', max_length=200)),
                ('prompt_hash', models.CharField(help_text='SHA-256 del prompt completo (sin almacenar PII directamente)', max_length=64)),
                ('response_summary', models.TextField(help_text='Resumen de la respuesta de IA (sin PII)')),
                ('ai_recommendation', models.JSONField(default=dict, help_text='Resultado estructurado de la recomendación IA')),
                ('sources_cited', models.JSONField(default=list, help_text='Fuentes RAG citadas por la IA')),
                ('hallucination_flags', models.JSONField(default=list, help_text='Alertas detectadas de posibles alucinaciones')),
                ('privacy_check_passed', models.BooleanField(default=True, help_text='Si el output pasó el control de privacidad por diseño')),
                ('human_decision', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('modified', 'Modificado con cambios')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('human_notes', models.TextField(blank=True, help_text='Comentarios del humano al aceptar, rechazar o modificar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_governance_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Gobernanza IA',
                'verbose_name_plural': 'Logs de Gobernanza IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(help_text='{question_id: answer_value}')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session_hash', models.CharField(help_text='Hash de sesión (no vinculado a identidad — privacidad por diseño)', max_length=64)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='leadership.qualityculturesurvey')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'session_hash')},
            },
        ),
        migrations.AddIndex(
            model_name='qualityculturesurvey',
            index=models.Index(fields=['organization_id', 'status'], name='leadership__organiz_01677f_idx'),
        ),
        migrations.AddIndex(
            model_name='managementreview',
            index=models.Index(fields=['organization_id', 'status'], name='leadership__organiz_2c61c0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencenode',
            index=models.Index(fields=['organization_id', 'node_type'], name='leadership__organiz_6f01ec_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencenode',
            index=models.Index(fields=['reference_model', 'reference_id'], name='leadership__referen_0506c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evidenceedge',
            unique_together={('source', 'target', 'edge_type')},
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['organization_id', 'workflow_type'], name='leadership__organiz_789bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['reference_model', 'reference_id'], name='leadership__referen_d53bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='aigovernancelog',
            index=models.Index(fields=['organization_id', 'operation'], name='leadership__organiz_871d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='aigovernancelog',
            index=models.Index(fields=['human_decision'], name='leadership__human_d_40923f_idx'),
        ),
        migrations.AddIndex(
            model_name='aigovernancelog',
            index=models.Index(fields=['organization_id', 'created_at'], name='leadership__organiz_e2211b_idx'),
        ),
    ]
